@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


package Model {
Class AddressBook
package Resident {
Class UniqueResidentList
Class Resident
Class Name
Class Phone
Class Email
Class Year
Class Room
}
}

AddressBook --> "1" UniqueResidentList
UniqueResidentList "1" --> "*" Resident
Resident *--> "1" Name
Resident *--> "1" Phone
Resident *--> "1"  Email
Resident *--> "1"  Year
Resident *--> "0..1"  Room
@enduml
