@startuml
start
:User enters email command 'emails';

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Parser parses command;
if () then ([command exist])
    :Logic executes the command;
    :Command retrieves list of Students;
    if () then ([more than 0 students])
        :Command concatenates students' emails;
        :Ui displays concatenated emails;
    else ([else])
        :Ui show error message;
    endif
else ([else])
    :Ui show error message;
endif
stop
@enduml
