@startuml
!include ../style.puml
title Adding a Grade

start
:User executes AddGradeCommand;

if () then ([all required prefixes present])
      :Parses the prefixes;

      if () then ([all prefixes formatted correctly])
      :Check if subject name has valid format;

          if () then ([subject name formatted correctly])
          :Check if graded item has valid format;

              if () then ([graded item formatted correctly])
              :Check if grade letter follows Singapore-GCE O'Level grading system;

                  if () then ([grade letter follows Singapore-GCE O'Level \ngrading system])
                  :Check if grade already existed;

                      if () then ([grade does not exist])
                      :Add grade to GradeBook;
                      :Show success message;

                      else ([else])

                      :Shows a grade already exist
                      error message;

                      endif

                  else ([else])
                  :Shows an invalid grade letter
                  error message;

                  endif

              else ([else])
              :Shows an invalid graded item
              error message;

              endif

          else ([else])
          :Shows an invalid subject name
          error message;

          endif

      else ([else])

      :Shows an error message on
      invalid prefix format;

      endif

else ([else])
    :Shows an invalid command error
    and command format message;

endif

stop

@enduml
