@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TutorTrackerParser" as TutorTrackerParser LOGIC_COLOR
participant ":ViewTimeTableCommandParser" as ViewTimeTableCommandParser LOGIC_COLOR
participant "v:ViewTimeTableCommand" as ViewTimeTableCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("timetable 2021-4-11")
activate LogicManager

LogicManager -> TutorTrackerParser : parseCommand("timetable 2021-4-11")
activate TutorTrackerParser

create ViewTimeTableCommandParser
TutorTrackerParser -> ViewTimeTableCommandParser
activate ViewTimeTableCommandParser

ViewTimeTableCommandParser --> TutorTrackerParser
deactivate ViewTimeTableCommandParser

TutorTrackerParser -> ViewTimeTableCommandParser : parse("2021-4-11")
activate ViewTimeTableCommandParser

create ViewTimeTableCommand
ViewTimeTableCommandParser -> ViewTimeTableCommand : ViewTimeTableCommand("2021-4-11")
activate ViewTimeTableCommand

ViewTimeTableCommand --> ViewTimeTableCommandParser : v
deactivate ViewTimeTableCommand

ViewTimeTableCommandParser --> TutorTrackerParser : v
deactivate ViewTimeTableCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewTimeTableCommandParser -[hidden]-> TutorTrackerParser
destroy ViewTimeTableCommandParser

TutorTrackerParser --> LogicManager : v
deactivate TutorTrackerParser

LogicManager -> ViewTimeTableCommand : execute()
activate ViewTimeTableCommand

ViewTimeTableCommand -> Model : viewTimetable()
activate Model

Model --> ViewTimeTableCommand
deactivate Model

create CommandResult
ViewTimeTableCommand -> CommandResult
activate CommandResult

CommandResult --> ViewTimeTableCommand
deactivate CommandResult

ViewTimeTableCommand --> LogicManager : result
deactivate ViewTimeTableCommand

[<--LogicManager
deactivate LogicManager
@enduml
