@startuml
!include ../style.puml
title Opening Timetable Window

start
:User executes ViewTimeTableCommand;

if () then ([correct command format])
      :Check if there is date parameter;

      if () then ([date argument is present])
      :Set the timetable's query date
      as the date parameter;

      else ([else])
      :Set the timetable's query date
      as today's date;

      endif
          :Show success message;

else ([else])
    :Shows an invalid command error
    and command format message;

endif

stop

@enduml
