@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam linetype ortho

Package Model <<Rectangle>>{
    Class AddressBook
    Class ModelManager

    Package Alias {
        Class AliasMapping
        Class Alias
    }
}

' ==== The model in question ====
ModelManager  --> "1" AliasMapping
ModelManager  ..> Alias
AddressBook  ..> Alias
AddressBook -down-> "1" AliasMapping
AliasMapping --> "*" Alias


@enduml
