@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam linetype ortho

Package Model <<Rectangle>>{
    Class StatefulAddressBook
    Class ModelManager

    Package CommandHistory {
        Class CommandHistory
        Class CommandHistoryEntry
    }
}
' ===== Overarching stuff =====
ModelManager *-left-> "1" StatefulAddressBook

' ==== The model in question ====
ModelManager  *---> CommandHistoryEntry
StatefulAddressBook --down-> CommandHistory
CommandHistory --> "*" CommandHistoryEntry


@enduml
