@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
    Class ModelManager

    Package CommandHistory {
        Class CommandHistory
        Class CommandHistoryEntry
    }
}

' ==== The model in question ====
ModelManager  -> "  1" CommandHistory
ModelManager  ..> CommandHistoryEntry
CommandHistory *--> "   *" CommandHistoryEntry


@enduml
