@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam linetype ortho

Package Model <<Rectangle>>{
    Class StatefulAddressBook
    Class ModelManager
    Package Room {
        Class UniqueRoomList
        Class Room
    }
}
' ===== Overarching stuff =====
ModelManager *-left-> "1" StatefulAddressBook

' ==== The model in question ====
ModelManager  *---> "      ~* filteredlist " Room
StatefulAddressBook --down-> UniqueRoomList
UniqueRoomList --> "*" Room


@enduml
