@startuml
'https://plantuml.com/sequence-diagram
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AliasCmdParser" as AliasCmdParser LOGIC_COLOR
participant "a:AliasCmd" as AliasCmd LOGIC_COLOR
participant "r:CmdResult" as CmdResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("alias a/h cmd/help")
activate LogicManager

LogicManager -> AddressBookParser : parseCmd(input)
activate AddressBookParser

create AliasCmdParser
AddressBookParser -> AliasCmdParser : parse(args)
activate AliasCmdParser
note right of AliasCmdParser
An alias object
is created.
Process is
omitted for
brevity.
end note
|||

create AliasCmd
AliasCmdParser -> AliasCmd : AliasCmd(alias)
activate AliasCmd

AliasCmd --> AliasCmdParser : a
deactivate AliasCmd

AliasCmdParser --> AddressBookParser : a
deactivate AliasCmdParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AliasCmdParser -[hidden]-> AddressBookParser
destroy AliasCmdParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AliasCmd : execute(model)
activate AliasCmd

AliasCmd -> Model : addAlias(alias)
activate Model
note left of Model
Storage process
omitted for
brevity.
end note

Model --> AliasCmd
deactivate Model
|||

create CmdResult
AliasCmd -> CmdResult
activate CmdResult

CmdResult --> AliasCmd : r
deactivate CmdResult

AliasCmd --> LogicManager : r
deactivate AliasCmd
AliasCmd -[hidden]-> AddressBookParser
destroy AliasCmd

[<--LogicManager : r
deactivate LogicManager
@enduml
