@startuml
'https://plantuml.com/activity-diagram-beta
!include ../style.puml

start
:User enters a command;
repeat :Parse command string;
if () then ([begins with existing command word])
:Parse as existing command;
if () then ([all parameters are valid)
:Return command;
stop
else ([else])
:Show error to user;
stop
endif
else ([else])
:Parse as alias;
if () then ([begins with alias])
:Replace alias with mapped command;
else ([else])
:Show error to user;
stop

@enduml
