@startuml
!include ../style.puml
start
:User enters command adding a issue;
:Parse command text;
if () then ([all parameters are valid])
    :Construct Issue
    with given parameters;
    if () then ([issue's room exists])
        if () then ([issue does not exist])
            :Add issue to SunRez;
            note left
            Adding the issue
            involves updating
            storage too. This
            process has been
            omitted for brevity.
            end note
            :Show success message to user;
        else ([else])
            :Show issue exists
            error to user;
            stop
        endif
    else ([else])
        :Show room does
        not exist error
        to user;
        stop
    endif
else ([else])
    :Show invalid usage
    error to user;
    stop
endif

stop
@enduml
