@startuml
!include ../style.puml

skinParam DefaultFontSize 12

box Logic LOGIC_COLOR_T1

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddRoomCommand" as cmd LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
Participant "model:Model" as model MODEL_COLOR
end box

' === Logic calls execute ===
-> logic ++: execute(cmdText)
note over logic
Command parsing
is ommitted for
brevity
end note

note over cmd
The construction of the command
sets the member variable toAdd
to the room to be added
end note

logic -> cmd : execute(model)
activate cmd

' === Check if room is in model ===
cmd -> model ++: hasRoom(toAdd)
return
' === End check if room is in model ===

opt model does not have room toAdd
' === Add room to model ===
cmd -> model ++: addRoom(toAdd)
return
' === End add room to model ===

' === Cmd commits the address book ===
cmd -> model ++: commitAddressBook()
return
' === End cmd commits the address book ===
end
logic <-- cmd
deactivate cmd
'Hidden arrow to position the destroy marker below the end of the activation bar.
<-[hidden]- cmd
destroy cmd
' === End Cmd commits the address book ===
<-- logic
deactivate logic




@enduml
