@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant "a:AddReminderCommand" as AddReminderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":ReminderTracker" as ReminderTracker MODEL_COLOR
end box

[-> AddReminderCommand : execute(m)
activate AddReminderCommand

AddReminderCommand -> AddReminderCommand : isBeforeToday()
activate AddReminderCommand
AddReminderCommand --> AddReminderCommand
deactivate AddReminderCommand

AddReminderCommand -> Model : hasReminder(r)
activate Model
Model -> ReminderTracker : hasReminder(r)
activate ReminderTracker
ReminderTracker --> Model
deactivate ReminderTracker
Model --> AddReminderCommand
deactivate Model

AddReminderCommand -> Model : addReminder(r)
activate Model

Model -> ReminderTracker : addReminder(r)
activate ReminderTracker

ReminderTracker --> Model
deactivate ReminderTracker

Model --> AddReminderCommand
deactivate Model

create CommandResult
AddReminderCommand -> CommandResult
activate CommandResult

CommandResult --> AddReminderCommand: r
deactivate CommandResult

[<--AddReminderCommand
deactivate AddReminderCommand
@enduml
