@startuml
start
:User executes add command;
:Parse command arguments;
:Create Method object based on parsed command;
:Create Address object based on parsed command;
:Create Header objects based on parsed command and add them to Headers Set;
:Create Tag objects based on parsed command and add them to Tags Set;

if () then ([else])
    :Create empty Data Object;
else ([Data arguments exist])
    :Create Data object based on parsed command;
endif

:Create Endpoint object from the Method, Address, Header Set, Tag Set and Data attributes
(Note: Reponse will be empty when an Endpoint is first created);

:Add the newly created endpoint to model's API endpoint list;
stop
@enduml
