@startuml
start
:User inputs add command;
:Taskify parses the input;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
if() then ([Valid input])
    if () then ([Task already exists])
        :Throw CommandException to the UI;
    else ([else])
        : Model adds Task to the list;
    endif
else ([else])
    :Throw ParseException to the UI;
endif

:UI displays success/error response to the user;
stop
@enduml
