@startuml
start
:User executes add command;
if () then ([owner])
:AddOwnerCommandParser processes;
elseif () then ([dog])
:AddDogCommandParser processes;
else ([program])
:AddProgramCommandParser processes;
endif
:Return AddCommand;
stop

@enduml
