@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "a:AddDateCommand" as AddDateCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add-date d/math exam dt/2022-03-03 0800")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add-date d/math exam dt/2022-03-03 0800")
activate AddressBookParser

ref over AddressBookParser, AddDateCommand : create AddDateCommand

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddDateCommand : execute()
activate AddDateCommand

AddDateCommand -> Model : addImportantDate(date)
activate Model

Model --> AddDateCommand
deactivate Model

create CommandResult
AddDateCommand -> CommandResult
activate CommandResult

CommandResult --> AddDateCommand
deactivate CommandResult

AddDateCommand --> LogicManager : result
deactivate AddDateCommand

[<--LogicManager
deactivate LogicManager
@enduml
