@startuml
'https://plantuml.com/activity-diagram-beta

start
:User inputs an add important date command;
:Command parsed by AddressBookParser;

if () then ([command word is valid])
    :Argument parsed by AddCommandParser;
    if () then ([argument is valid])
        :Creates a new ImportantDate object;
        :Returns AddDateCommand;
        :Checks if important date created is in TutorsPet;
        if () then ([present])
            :CommandException is thrown;
        else ([else])
            :Adds the important date;
        endif
    else ([else])
        :ParseException is thrown;
    endif
else ([else])
    :ParseException is thrown;
endif

stop

@enduml
