@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "cmd:AddPictureCommand" as AddPictureCommand LOGIC_COLOR
participant "<<class>>\n:FileUtil"  as FileUtil LOGIC_COLOR
participant "p:Person" as Person LOGIC_COLOR
participant "oldPic:Picture" as OldPicture LOGIC_COLOR
participant "pic:Picture" as Picture LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> AddPictureCommand : execute()
activate AddPictureCommand

AddPictureCommand -> FileUtil : validateFile(filepath)
activate FileUtil

FileUtil --> AddPictureCommand : validationResult
deactivate FileUtil

AddPictureCommand -> Model : get person to edit
activate Model

Model --> AddPictureCommand : p
deactivate Model

AddPictureCommand -> AddPictureCommand : generateNewFilename()
activate AddPictureCommand

AddPictureCommand --> AddPictureCommand : newFileName
deactivate AddPictureCommand

AddPictureCommand -> FileUtil : copyFile(filepath, newFilePath)
activate FileUtil

FileUtil --> AddPictureCommand
deactivate FileUtil

create Picture
AddPictureCommand -> Picture
activate Picture

Picture --> AddPictureCommand : picture
deactivate Picture

AddPictureCommand -> Person : deletePicture()
activate Person

Person --> AddPictureCommand
deactivate Person

AddPictureCommand -> Person : withPicture(picture)
activate Person

Person --> AddPictureCommand
deactivate Person

AddPictureCommand -> Model : update p
activate Model

Model --> AddPictureCommand
deactivate Model

create CommandResult
AddPictureCommand -> CommandResult
activate CommandResult

CommandResult --> AddPictureCommand
deactivate CommandResult

[<--AddPictureCommand : result
deactivate AddPictureCommand

@enduml
