@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "descriptor:AddOrderDescriptor" as AddOrderDescriptor LOGIC_COLOR
participant ":IndexList" as IndexList LOGIC_COLOR
participant ":AddCommand" as AddCommand LOGIC_COLOR
'participant "cr:CommandResult" as CommandResult LOGIC_COLOR
end box

'box Model MODEL_COLOR_T1
'participant ":Model" as Model MODEL_COLOR
'end box

'is omitting arguments okay, this argument is too long
[-> AddCommandParser : parse("n/Alex")
activate AddCommandParser

create AddOrderDescriptor
AddCommandParser -> AddOrderDescriptor
activate AddOrderDescriptor

'italics?
'is the return arrow supposed to be descriptor or both
AddOrderDescriptor --> AddCommandParser : descriptor
deactivate AddOrderDescriptor

create IndexList
AddCommandParser -> IndexList
activate IndexList
IndexList --> AddCommandParser : indexlist
deactivate IndexList

create AddCommand
AddCommandParser -> AddCommand : new AddCommand(descriptor, indexlist)
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

[<-- AddCommandParser : a
deactivate AddCommandParser
[<-[hidden]- AddCommandParser
destroy AddCommandParser


@enduml
