@startuml
!include style.puml
'https://plantuml.com/sequence-diagram
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PawbookParser" as PawbookParser LOGIC_COLOR
participant ":AddOwnerCommandParser" as AddOwnerCommandParser LOGIC_COLOR
participant "s:AddOwnerCommand" as AddOwnerCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("add owner n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney")
activate LogicManager

LogicManager -> PawbookParser : parseCommand("add owner n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney")
activate PawbookParser

create AddOwnerCommandParser
PawbookParser -> AddOwnerCommandParser
activate AddOwnerCommandParser

AddOwnerCommandParser --> PawbookParser
deactivate AddOwnerCommandParser

PawbookParser -> AddOwnerCommandParser : parse("n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney")
activate AddOwnerCommandParser

create AddOwnerCommand
AddOwnerCommandParser -> AddOwnerCommand
activate AddOwnerCommand

AddOwnerCommand --> AddOwnerCommandParser : s
deactivate AddOwnerCommand

AddOwnerCommandParser --> PawbookParser : s
deactivate AddOwnerCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddOwnerCommandParser -[hidden]-> PawbookParser
destroy AddOwnerCommandParser

PawbookParser --> LogicManager : s
deactivate PawbookParser

LogicManager -> AddOwnerCommand : execute()
activate AddOwnerCommand

AddOwnerCommand -> Model : addEntity(toAdd)
activate Model

Model --> AddOwnerCommand
deactivate Model

create CommandResult
AddOwnerCommand -> CommandResult
activate CommandResult

CommandResult --> AddOwnerCommand
deactivate CommandResult

AddOwnerCommand --> LogicManager : result
deactivate AddOwnerCommand

[<--LogicManager
deactivate LogicManager
@enduml
