@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AddressBookStorage <<Interface>>
Interface AppointmentBookStorage <<Interface>>

note "Interface with appointment book methods,\nsimilar to AddressBookStorage" as N1
N1 .left. AppointmentBookStorage

Class StorageManager
Class JsonUserPrefsStorage
Class JsonAddressBookStorage
Class JsonAppointmentBookStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> AddressBookStorage

Storage -|> UserPrefsStorage
Storage -|> AddressBookStorage
Storage -|> AppointmentBookStorage

StorageManager o--> AppointmentBookStorage
AddressBookStorage -right[hidden]-> AppointmentBookStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAppointmentBookStorage .up.|> AppointmentBookStorage
JsonAppointmentBookStorage .down.> JsonSerializableAppointmentBook
JsonAddressBookStorage .down.> JsonSerializableAddressBook
JsonSerializableAppointmentBook .down.> JsonAdaptedAppointment
JsonSerializableAddressBook .down.> JsonAdaptedContact
JsonAdaptedAppointment .down.> JsonAdaptedTag

JsonAdaptedContact .down.> JsonAdaptedTag

@enduml
