@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyAppointmentBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class AppointmentBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Contact {
Class Contact
Class UniqueContactList
'Class Phone
'Class Email
}

'Package Tag {
'Class Tag
'Class ChildTag
'}

'Class Address
'Class Name

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
AppointmentBook .up.|> ReadOnlyAppointmentBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueContactList
UniqueContactList o--> "*" Contact

ModelManager ----->"~* filtered list" Contact

ModelManager o--> "1" AppointmentBook

Package Appointment {
Class Appointment
Class UniqueAppointmentList
'Class DateTime
}

AppointmentBook *--> "1" UniqueAppointmentList
UniqueAppointmentList o--> "*" Appointment

'Tag <|- ChildTag

'Contact ----> "1" Name
'Contact ----> Address
'Contact ----> Email
'Contact ----> Phone
'Contact ----> "~*" Tag
'
'Appointment ----> "1" Name
'Appointment ----> "*" Address
'Appointment --> "*" DateTime
'Appointment ---> "~*" Contact
'Appointment --> "~*" Tag

ModelManager ----> "filtered list *" Appointment

@enduml
