@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0
skinparam classAttributeFontColor #white

Class Appointment {
    -name: String
    -location: String
    -date: DateTime
    -contacts: ArrayList<Person>

}
note top of Appointment: classified under Model

Class UniqueAppointmentList
Class Person

Appointment -> "*" Person
UniqueAppointmentList --> "*" Appointment

show attributes

@enduml