@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyAppointmentBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class AppointmentBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Contact {
Class Contact
Class UniqueContactList
}

Class Address
Class Name
note "Name and Address, classes previously in Contact package" as N1
Name .. N1
Address .. N1

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook ..|> ReadOnlyAddressBook
AppointmentBook ..|> ReadOnlyAppointmentBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueContactList
UniqueContactList o--> "*" Contact

ModelManager -->"filtered list ~*" Contact

ModelManager o--> "1" AppointmentBook

Package Appointment {
Class Appointment
Class UniqueAppointmentList
Class DateTime
}

AppointmentBook *--> "1" UniqueAppointmentList
UniqueAppointmentList o--> "*" Appointment

Contact ---> Name
Contact ---> Address

Appointment ----> "name 1" Name
Appointment ----> "*" Address
Appointment --> "*" DateTime
Appointment ---> "~* contact" Contact

ModelManager -->"filtered list *" Appointment
note "Possible design considerations for ModelManager:\n- 2 subclass, one for Contact and one for Appointment\n- As an implementation of the Model interface,\n  ModelManager can handle both" as N3

note "Extra: Tag functions" as N4
N4 .left. Appointment

@enduml
