@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":BudgetBabyLogic" as logic LOGIC_COLOR
Participant ":BudgetBabyModel" as model MODEL_COLOR
Participant ":BudgetBabyStorage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "add-fr d/desc a/amount c/category"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("add-fr d/desc a/amount c/category")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : addFinancialRecord(fr)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic -[LOGIC_COLOR]> storage : saveBudgetTracker(budgetTracker)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
storage --[STORAGE_COLOR]> storage
deactivate storage

storage --[STORAGE_COLOR]> logic
deactivate storage

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
