@startuml
!include style.puml
hide stereotypes

Actor User as user USER_COLOR
Participant ":UI" as ui <<ui>> UI_COLOR
Participant ":Logic" as logic <<logic>> LOGIC_COLOR
Participant ":Model" as model <<model>> MODEL_COLOR
Participant ":Storage" as storage <<storage>> STORAGE_COLOR

user -[USER_COLOR]> ui : executeCommand\n("customer delete 1")
activate ui UI_COLOR UI_COLOR_DARK

ui -[UI_COLOR]> logic : execute\n("customer delete 1")
activate logic LOGIC_COLOR LOGIC_COLOR_DARK

logic -[LOGIC_COLOR]> model : deletePerson(p)
activate model MODEL_COLOR MODEL_COLOR_DARK

model -[MODEL_COLOR]-> logic
deactivate model

logic -[LOGIC_COLOR]> storage : savePersonBook(personBook)
activate storage STORAGE_COLOR STORAGE_COLOR_DARK

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
storage --[STORAGE_COLOR]> storage
deactivate storage

storage --[STORAGE_COLOR]> logic
deactivate storage

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
