@startuml AutocompleteSequenceDiagram
!include style.puml

box UI UI_COLOR_T1
participant ":UI" as UI UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AutocompleteParser" as AutocompleteParser LOGIC_COLOR
participant ":AutocompleteUtil" as AutocompleteUtil LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> UI : "edit 1 -r TAB"
activate UI

UI-> LogicManager : autoComplete("edit 1 -r")
activate LogicManager

LogicManager -> AutocompleteParser : parseCommand("edit 1 -r")
activate AutocompleteParser

create AutocompleteUtil
AutocompleteParser -> AutocompleteUtil
activate AutocompleteUtil

AutocompleteUtil -> AutocompleteParser
deactivate AutocompleteUtil

AutocompleteParser -> LogicManager
deactivate AutocompleteParser

LogicManager -> AutocompleteUtil : parse()
activate AutocompleteUtil

AutocompleteUtil -> Model : get()
activate Model

Model -> AutocompleteUtil : PersonList/EventList
deactivate Model

AutocompleteUtil -> LogicManager : commandResult
deactivate AutocompleteUtil

LogicManager -> UI : commandResult
deactivate LogicManager

UI ->[ : commandResult
deactivate UI
@enduml
