@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePassengerList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePassengerList
UniqueTagList -[hidden]down- UniquePassengerList

UniqueTagList *-right-> "*" Tag
UniquePassengerList o-right-> Passenger

Passenger -up-> "*" Tag

Passenger *--> Name
Passenger *--> Phone
Passenger *--> Address
Passenger *--> TripDay
Passenger *--> TripTime
Passenger *--> "0..1" Price
Passenger *--> "0..1" Driver
@enduml
