@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

FlashcardBook *-right-> "1" UniqueFlashcardList
FlashcardBook *-right-> "1" UniqueTagList
FlashcardBook *-down-> "1" UniqueScoreHistoryList
UniqueTagList -[hidden]down- UniqueFlashcardList
UniqueTagList -[hidden]down- UniqueFlashcardList

UniqueTagList *-right-> "*" Tag
UniqueFlashcardList o-right-> "*"Flashcard

Flashcard -up-> "*" Tag
Flashcard *--> Question
Flashcard *--> Answer

UniqueScoreHistoryList o-down-> "*"Score
@enduml
