@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Wardrobe *-right-> "1" UniqueGarmentList
Wardrobe *-right-> "1" UniqueDescriptionList
UniqueDescriptionList -[hidden]down- UniqueGarmentList
UniqueDescriptionList -[hidden]down- UniqueGarmentList

UniqueDescriptionList *-right-> "*" Description
UniqueGarmentList o-right-> Garment

Garment -up-> "*" Description

Garment *--> Name
Garment *--> Size
Garment *--> Colour
Garment *--> DressCode
Garment *--> Type
Garment *--> LastUse
@enduml
