@startuml
start
:User inputs 'borrow r/Tom b/Cloud Atlas';

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid input])
    :execute command;
    :addRecord;
    :updateBookStatus;
    :updateReaderStatus;
    :borrow success;
else ([input invalid or check condition failed])
    :command invalid;
endif
stop
@enduml
