@startuml
!include style.puml
box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WeeblingoParser" as WeeblingoParser LOGIC_COLOR
participant ":CheckCommandParser" as CheckCommandParser LOGIC_COLOR
participant ":CheckCommand" as CheckCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

[-> MainWindow : executeCommand(\n"check o")
activate MainWindow

MainWindow -> LogicManager : execute("check o")
activate LogicManager

LogicManager -> WeeblingoParser : parseCommand(\n"check o")
activate WeeblingoParser

create CheckCommandParser
WeeblingoParser -> CheckCommandParser :
activate CheckCommandParser

CheckCommandParser --> WeeblingoParser :
deactivate CheckCommandParser

WeeblingoParser -> CheckCommandParser : parse("o")
activate CheckCommandParser

create CheckCommand
CheckCommandParser -> CheckCommand :
activate CheckCommand

CheckCommand --> CheckCommandParser :
deactivate CheckCommand

CheckCommandParser --> WeeblingoParser :
deactivate CheckCommandParser

CheckCommandParser -[hidden]-> WeeblingoParser
destroy CheckCommandParser

WeeblingoParser --> LogicManager :
deactivate WeeblingoParser

LogicManager -> CheckCommand : execute(model)
activate CheckCommand

CheckCommand -> ModelManager : isCorrectAttempt("o")
activate ModelManager

ModelManager --> CheckCommand :
deactivate ModelManager

create CommandResult
CheckCommand -> CommandResult
activate CommandResult

CommandResult --> CheckCommand
deactivate CommandResult

CheckCommand --> LogicManager : result
deactivate CheckCommand

MainWindow<--LogicManager : result
deactivate LogicManager

MainWindow -> LogicManager : getCurrentIndex()
activate LogicManager

LogicManager -> ModelManager : getCurrentIndex()
activate ModelManager

LogicManager <-- ModelManager : index
deactivate ModelManager

MainWindow <-- LogicManager : index
deactivate LogicManager

MainWindow -> LogicManager : showAnswer()
activate LogicManager

LogicManager -> ModelManager : getCurrentMode()
activate ModelManager

LogicManager <-- ModelManager : mode
deactivate ModelManager

MainWindow <-- LogicManager  : showAnswer
deactivate LogicManager


MainWindow -> MainWindow : \nupdateCard(\nindex, \nshowAnswer)
activate MainWindow

LogicManager -[hidden]-> LogicManager : result
deactivate MainWindow

[<--MainWindow
deactivate MainWindow
@enduml
