@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StoreMandoParser" as StoreMandoParser LOGIC_COLOR
participant ":ClearCommandParser" as ClearCommandParser LOGIC_COLOR
participant "command:ClearCommand" as ClearCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("clear")
activate LogicManager

LogicManager -> StoreMandoParser : parseCommand("clear")
activate StoreMandoParser

create ClearCommandParser
StoreMandoParser -> ClearCommandParser
activate ClearCommandParser

ClearCommandParser --> StoreMandoParser
deactivate ClearCommandParser

StoreMandoParser -> ClearCommandParser : parse()
activate ClearCommandParser

create ClearCommand
ClearCommandParser -> ClearCommand :
activate ClearCommand

ClearCommand --> ClearCommandParser : command
deactivate ClearCommand

ClearCommandParser --> StoreMandoParser : command
deactivate ClearCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
ClearCommandParser -[hidden]-> StoreMandoParser
destroy ClearCommandParser

StoreMandoParser --> LogicManager : command
deactivate StoreMandoParser

LogicManager -> ClearCommand : execute(model)
activate ClearCommand

ClearCommand -> Model : clearLocation(predicate)
activate Model

Model --> ClearCommand
deactivate Model

ClearCommand -> Model : updateFilteredItemList()
activate Model

Model --> ClearCommand
deactivate Model

create CommandResult
ClearCommand -> CommandResult
activate CommandResult

CommandResult --> ClearCommand : result
deactivate CommandResult

ClearCommand --> LogicManager : result
deactivate ClearCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
