@startuml
start
:User executes clear command;
:Command is parsed;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Command is valid])
    :Clear location in StoreMando;
else ([else])
    :Display parse error message;
endif
stop
@enduml
