@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes Clear command;
if () then ([user input is valid])
    :Replace delivery list with a new empty one;
    :Show success message;
else ([else])
    :Show unknown command message;
endif
stop
@enduml
