@startuml
start
: User enters clear location command;
: Parse user input;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([User input is valid])
    : Create and execute ClearCommand;
    : Clear all items in the location from StoreMando inventory;
    : Display command success message;
else ([Else])
    : Display parse error message;
endif
stop
@enduml
