@startuml
start
:User executes Add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([input is valid & student does not exist in Student Book])
    :Parse Command;
    :Save new student to StudentBook;
else ([else])
endif
stop
@enduml
