@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command adds, edits, or deletes appointments])
    :Purge redundant states;
    :Save AppointmentBook to
    previousAppointmentLists;
else ([else])
endif
stop
@enduml
