@startuml
!include style.puml

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
participant ":List<? extends DisplayableContent>" as List MODEL_COLOR
end box

box Content LOGIC_COLOR_T1
participant ":Content" as ContentObj LOGIC_COLOR
end box

box Index UI_COLOR_T1
participant ":Index" as Index UI_COLOR
end box

box Note STORAGE_COLOR_T1
participant "createdNote:Note" as Note STORAGE_COLOR
end box


[-> Model: executeCommand("copytonote 1")
activate Model

Model -> List : getFilteredCurrentDictionaryList()
activate List

List -> ContentObj : get(targetIndex)
activate ContentObj

ContentObj -> Index : getZeroBased()
activate Index
Index --> ContentObj
deactivate Index
ContentObj --> List
deactivate ContentObj
List -> ContentObj : getDictionaryContent()
activate ContentObj
ContentObj --> List
deactivate ContentObj
deactivate List

create Note
Model -> Note : new Note(contentToAdd)
activate Note

Note --> Model
deactivate Note

Model -> Model: addNote()
activate Model
Model --> Model
deactivate Model

[<--Model
deactivate Model
@enduml
