@startuml
'https://plantuml.com/activity-diagram-beta

start
:User inputs a delete important date command;
:Command parsed by AddressBookParser;

if () then ([command word is valid])
    :Argument parsed by DeleteDateCommandParser;
    if () then ([argument is valid])
        :Returns DeleteDateCommand;
        :Checks if important date specified is in TutorsPet;
        if () then ([present])
            :Deletes the important date;
        else ([else])
             :CommandException is thrown;
        endif
    else ([else])
        :ParseException is thrown;
    endif
else ([else])
    :ParseException is thrown;
endif

stop

@enduml
