@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ColabParser" as ColabParser LOGIC_COLOR
participant ":DeleteProjectCommandParser" as DeleteProjectCommandParser LOGIC_COLOR
participant "d:DeleteProjectCommand" as DeleteProjectCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteP 1")
activate LogicManager

LogicManager -> ColabParser : parseCommand("deleteP 1")
activate ColabParser

create DeleteProjectCommandParser
ColabParser -> DeleteProjectCommandParser
activate DeleteProjectCommandParser

DeleteProjectCommandParser --> ColabParser
deactivate DeleteProjectCommandParser

ColabParser -> DeleteProjectCommandParser : parse("1")
activate DeleteProjectCommandParser

create DeleteProjectCommand
DeleteProjectCommandParser -> DeleteProjectCommand
activate DeleteProjectCommand

DeleteProjectCommand --> DeleteProjectCommandParser : d
deactivate DeleteProjectCommand

DeleteProjectCommandParser --> ColabParser : d
deactivate DeleteProjectCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteProjectCommandParser -[hidden]-> ColabParser
destroy DeleteProjectCommandParser

ColabParser --> LogicManager : d
deactivate ColabParser

LogicManager -> DeleteProjectCommand : execute()
activate DeleteProjectCommand

DeleteProjectCommand -> Model : deleteProject(1)
activate Model

Model --> DeleteProjectCommand
deactivate Model

create CommandResult
DeleteProjectCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteProjectCommand
deactivate CommandResult

DeleteProjectCommand --> LogicManager : result
deactivate DeleteProjectCommand

[<--LogicManager
deactivate LogicManager
@enduml
