@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":DeleteGroupCommand" as AddGroupCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":GroupHashMap" as GroupMap MODEL_COLOR
end box

[-> AddGroupCommand : execute()
activate AddGroupCommand

AddGroupCommand -> Model : getFilteredPersonList()
activate Model

Model --> AddGroupCommand : filteredList
deactivate Model

AddGroupCommand -> Model : getGroupMap().getOrDefault()
activate Model

	Model -> GroupMap : getOrDefault()
	GroupMap --> Model : group

loop for all indexes
Model --> AddGroupCommand : group
deactivate Model


	AddGroupCommand -> Model : deleteGroup(group)
	activate Model

	Model --> AddGroupCommand
	deactivate Model
AddGroupCommand -> CommandResult **
activate CommandResult

CommandResult --> AddGroupCommand : result
deactivate CommandResult
[<-- AddGroupCommand : result
deactivate AddGroupCommand
@enduml
