@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StoreMandoParser" as StoreMandoParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "command:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 5")
activate LogicManager

LogicManager -> StoreMandoParser : parseCommand("delete 5")
activate StoreMandoParser

create DeleteCommandParser
StoreMandoParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> StoreMandoParser
deactivate DeleteCommandParser

StoreMandoParser -> DeleteCommandParser : parse("5")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : command
deactivate DeleteCommand

DeleteCommandParser --> StoreMandoParser : command
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> StoreMandoParser
destroy DeleteCommandParser

StoreMandoParser --> LogicManager : command
deactivate StoreMandoParser

LogicManager -> DeleteCommand : execute(model)
activate DeleteCommand

DeleteCommand -> Model : getFilteredItemList()
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : deleteItem(5)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand : result
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
