@startuml
start
:User executes delete command;
if () then ([owner])
:DeleteOwnerCommandParser processes;
elseif () then ([dog])
:DeleteDogCommandParser processes;
else ([program])
:DeleteProgramCommandParser processes;
endif
:returns DeleteCommand;
stop

@enduml
