@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DeliveryListParser" as DeliveryListParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "command:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 3")
activate LogicManager

LogicManager -> DeliveryListParser : parseCommand("delete 3")
activate DeliveryListParser

create DeleteCommandParser
DeliveryListParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> DeliveryListParser
deactivate DeleteCommandParser

DeliveryListParser -> DeleteCommandParser : parse("3")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : command
deactivate DeleteCommand

DeleteCommandParser --> DeliveryListParser : command
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> DeliveryListParser
destroy DeleteCommandParser

DeliveryListParser --> LogicManager : command
deactivate DeliveryListParser

LogicManager -> DeleteCommand : execute(model)
activate DeleteCommand

DeleteCommand -> Model : getFilteredCustomerList()
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : deleteCustomer(3)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand : result
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
