@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":BookingSystemParser" as BookingSystemParser LOGIC_COLOR
participant ":DeleteBookingCommandParser" as DeleteBookingCommandParser LOGIC_COLOR
participant "d:DeleteBookingCommand" as DeleteBookingCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete_booking 1")
activate LogicManager

LogicManager -> BookingSystemParser : parseCommand("delete_booking 1")
activate BookingSystemParser

create DeleteBookingCommandParser
BookingSystemParser -> DeleteBookingCommandParser
activate DeleteBookingCommandParser

DeleteBookingCommandParser --> BookingSystemParser
deactivate DeleteBookingCommandParser

BookingSystemParser -> DeleteBookingCommandParser : parse("1")
activate DeleteBookingCommandParser

create DeleteBookingCommand
DeleteBookingCommandParser -> DeleteBookingCommand
activate DeleteBookingCommand

DeleteBookingCommand --> DeleteBookingCommandParser : d
deactivate DeleteBookingCommand

DeleteBookingCommandParser --> BookingSystemParser : d
deactivate DeleteBookingCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteBookingCommandParser -[hidden]-> BookingSystemParser
destroy DeleteBookingCommandParser

BookingSystemParser --> LogicManager : d
deactivate BookingSystemParser

LogicManager -> DeleteBookingCommand : execute()
activate DeleteBookingCommand

DeleteBookingCommand -> Model : deletePerson(1)
activate Model

Model --> DeleteBookingCommand
deactivate Model

create CommandResult
DeleteBookingCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteBookingCommand
deactivate CommandResult

DeleteBookingCommand --> LogicManager : result
deactivate DeleteBookingCommand

[<--LogicManager
deactivate LogicManager
@enduml
