
@startuml
start
:User executes command;
:Check input;
if() then ([user input is valid])
    :Create delete command;
    :find the targeted module;
    if() then ([if module exists])
        : Retrieve Module from uniqueModuleList;
        :Find the target assignment in the module;
        if() then ([assignment exists)
                : Delete the assignment from the module;
                : Show successful command result;
        else([assignment does not exist])
            : Show error message to user;
        endif
    else([if module does not exist])
        :Show error message to user;
    endif
else([user input is invalid])
    :Show error message to user;
endif
stop
@enduml
