@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DetailCommandParser" as DetailCommandParser LOGIC_COLOR
participant "d:DetailCommand" as DetailCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("detail 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("detail 1")
activate AddressBookParser

create DetailCommandParser
AddressBookParser -> DetailCommandParser
activate DetailCommandParser

DetailCommandParser --> AddressBookParser
deactivate DetailCommandParser

AddressBookParser -> DetailCommandParser : parse("1")
activate DetailCommandParser

create DetailCommand
DetailCommandParser -> DetailCommand
activate DetailCommand

DetailCommand --> DetailCommandParser : d
deactivate DetailCommand

DetailCommandParser --> AddressBookParser : d
deactivate DetailCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DetailCommandParser -[hidden]-> AddressBookParser
destroy DetailCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DetailCommand : execute()
activate DetailCommand

DetailCommand -> Model : setSelectedPerson(personToDisplay)
activate Model

Model --> DetailCommand
deactivate Model

create CommandResult
DetailCommand -> CommandResult
activate CommandResult

CommandResult --> DetailCommand
deactivate CommandResult

DetailCommand --> LogicManager : result
deactivate DetailCommand

[<--LogicManager
deactivate LogicManager
@enduml
