@startuml
start
:User executes done command;

if () then ([is valid command])

    if () then ([Status is 'done'])
    :Throw new
    CommandException;
    :Display task already
    done message;

    else ([Status is 'not done'])
    :Create new Task with
    Status attribute set
    to 'done';
    :Update model with the
    new Task;
    :Return doneCommand
    success message;
    endif

else ([invalid command])
        :Display relevant
        error message;

endif
stop
@enduml
