@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes drop command;
if () then ([dogID valid)
else ([programID valid])
endif
:DropCommandParser processes;
:returns DropCommand;
stop

@enduml
