@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":RemindMeParser" as RemindMeParser LOGIC_COLOR
participant ":EditAssignmentCommandParser" as EditAssignmentCommandParser LOGIC_COLOR
participant "command:EditAssignmentCommand" as EditAssignmentCommand LOGIC_COLOR
participant "commandResult:CommandResult" as CommandResult LOGIC_COLOR
end box

box Storage
participant ":Storage" as Storage STORAGE_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":RemindMe" as RemindMe MODEL_COLOR


end box

[-> LogicManager : execute("edit m/CS2103 a/1 d/Tut2")
activate LogicManager

LogicManager -> RemindMeParser : parseCommand("edit m/CS2103 a/1 d/Tut2")
activate RemindMeParser

create EditAssignmentCommandParser
RemindMeParser -> EditAssignmentCommandParser
activate EditAssignmentCommandParser
EditAssignmentCommandParser --> RemindMeParser
RemindMeParser -> EditAssignmentCommandParser : parse("m/CS2103 a/1 d/Tut2")

create EditAssignmentCommand
EditAssignmentCommandParser -> EditAssignmentCommand
activate EditAssignmentCommand
EditAssignmentCommand --> EditAssignmentCommandParser : command
deactivate EditAssignmentCommand

EditAssignmentCommandParser --> RemindMeParser : command
deactivate EditAssignmentCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
EditAssignmentCommandParser -[hidden]-> RemindMeParser
destroy EditAssignmentCommandParser

RemindMeParser --> LogicManager : command
deactivate RemindMeParser

LogicManager -> EditAssignmentCommand : execute()
activate EditAssignmentCommand

EditAssignmentCommand -> Model : getModule(CS2103)
activate Model
Model --> EditAssignmentCommand
EditAssignmentCommand -> Model : editAssignment(m, 1, Tut2)
ref over Model, RemindMe : editAssignment(m, 1, Tut2)
Model --> EditAssignmentCommand
deactivate Model


create CommandResult
EditAssignmentCommand -> CommandResult
activate CommandResult

CommandResult --> EditAssignmentCommand
deactivate CommandResult

EditAssignmentCommand --> LogicManager : result
deactivate EditAssignmentCommand


LogicManager -> Storage : saveRemindMe()
activate Storage
Storage --> LogicManager
deactivate Storage

[<--LogicManager
deactivate LogicManager
@enduml
