@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR


Class "<<Interface>>\nParser"
Class SocheduleParser
Class EditEventCommandParser
Class EditEventDescriptor
Class SocheduleParserUtil
Class EditEventCommand

Class HiddenOutside #FFFFFF

HiddenOutside ..> SocheduleParser
SocheduleParser .left.> EditEventCommandParser: creates >

EditEventCommandParser ..> EditEventCommand : creates >
EditEventCommandParser .left.> SocheduleParserUtil
EditEventCommandParser ..> EditEventDescriptor : creates >
EditEventCommandParser .up.|> "<<Interface>>\nParser"

EditEventCommand -->"1" EditEventDescriptor

@enduml
