@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters edit command;
:Parse user input;
if () then ([Index > number of items in StoreMando])
    : Display parse error message;
else ([else])
    if () then ([Input matches the edit command format)
        :Item's attributes update accordingly;
        :A success message is displayed to the user;
    else ([else])
        : Display parse error message;
    endif
endif
stop

@enduml
