
@startuml
start
:User executes command;
if() then ([user input is valid])
    :Create edit command to find targeted Module and Assignment;
    if() then ([if module exists])
        if() then ([assignment exists)

            if () then ([content is valid to edit])
                : change the corresponding assignment and module and place it back to UniqueModuleList;
                : show successful command result;
            else([content is invalid to edit])
                : show error message to user;
            endif

        else([assignment does not exist])
            : show error message to user;
        endif

    else([if module does not exist])
        :Show error message to user;
    endif
else([user input is invalid])
    :Show error message to user;
endif
stop
@enduml
