@startuml
!include style.puml
'https://plantuml.com/sequence-diagram
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PawbookParser" as PawbookParser LOGIC_COLOR
participant ":EditOwnerCommandParser" as EditOwnerCommandParser LOGIC_COLOR
participant "s:EditOwnerCommand" as EditOwnerCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("edit owner 1 n/John Doe t/friend")
activate LogicManager

LogicManager -> PawbookParser : parseCommand("edit owner 1 n/John Doe t/friend")
activate PawbookParser

create EditOwnerCommandParser
PawbookParser -> EditOwnerCommandParser
activate EditOwnerCommandParser

EditOwnerCommandParser --> PawbookParser
deactivate EditOwnerCommandParser

PawbookParser -> EditOwnerCommandParser : parse("1 n/John Doe t/friend")
activate EditOwnerCommandParser

create EditOwnerCommand
EditOwnerCommandParser -> EditOwnerCommand
activate EditOwnerCommand

EditOwnerCommand --> EditOwnerCommandParser : s
deactivate EditOwnerCommand

EditOwnerCommandParser --> PawbookParser : s
deactivate EditOwnerCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditOwnerCommandParser -[hidden]-> PawbookParser
destroy EditOwnerCommandParser

PawbookParser --> LogicManager : s
deactivate PawbookParser

LogicManager -> EditOwnerCommand : execute()
activate EditOwnerCommand

EditOwnerCommand -> Model : setEntity(targetId, editedEntity)
activate Model

Model --> EditOwnerCommand
deactivate Model

create CommandResult
EditOwnerCommand -> CommandResult
activate CommandResult

CommandResult --> EditOwnerCommand
deactivate CommandResult

EditOwnerCommand --> LogicManager : result
deactivate EditOwnerCommand

[<--LogicManager
deactivate LogicManager
@enduml