@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes enrol command;
if () then ([dogId valid])
else ([programId valid])
endif
:EnrolCommandParser processes;
:returns EnrolCommand;
stop

@enduml
