@startuml
skinparam arrowThickness 1.1
skinparam classAttributeIconSize 0

hide circle

class EntryName {
  + {static} NAME_CONSTRAINTS : String
  + {static} VALIDATION_REGEX : String
  + name : String

  + {static} isValidName() : boolean
  + EntryName(String)
}

class EntryDate {
  + {static} DATE_CONSTRAINTS : String
  + value : LocalDateTime

  + {static} isValidDate() : boolean
  + DateTime(String)
}

class Tag {
  + {static} MESSAGE_CONSTRAINTS : String
  + {static} VALIDATION_REGEX : String
  + tagName : string

  + {static} isValidTagName() : boolean
  + Tag(String)
}

class Entry {
  - entryName: EntryName
  - startDate : EntryDate
  - endDate : EntryDate
  - tags : HashSet<Tag>

  + Entry(...)
}

Entry -right-> "1" EntryName
Entry -down-> "2" EntryDate
EntryDate -right[hidden]-> Tag
EntryName -down[hidden]-> Tag
Entry -> "*" Tag

@enduml
