@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "{abstract}\nEvent" as Event

Schedule -up-|> Event
Appointment -up-|> Event
Event *-right-> TimeFrom
Event *-left-> TimeTo

ScheduleTracker *-right-> "1" ScheduleList
ScheduleList o-right-> Schedule

Schedule *--> Title
Schedule *--> Description

AppointmentBook *-left-> "1" AppointmentList
AppointmentList o-left-> Appointment

Appointment *--> Name
Appointment *--> Subject
Appointment *--> Location

@enduml
