@startuml
!include style.puml
mainframe "sd execute method of important dates command"

box Logic LOGIC_COLOR_T1
participant "d:ImportantDatesCommand" as ImportantDatesCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

ImportantDatesCommand -> Model : updateSortedImportantDatesList(new ImportantDateDetailsComparator())
activate Model

Model --> ImportantDatesCommand
deactivate Model

create CommandResult
ImportantDatesCommand -> CommandResult
activate CommandResult

CommandResult --> ImportantDatesCommand
deactivate CommandResult
@enduml
