@startuml
start
:User enters find command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
:Parse user input;
if () then ([user input is valid])
    :Create and execute FindCommand;
    :Display filtered list;
    :Display command success message;
else ([else])
    :Display parse error message;
endif
stop
@enduml
