@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SocheduleParser" as SocheduleParser LOGIC_COLOR
participant ":FindEventCommandParser" as FindEventCommandParser LOGIC_COLOR
participant "d:FindEventCommand" as FindEventCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find_event meeting")
activate LogicManager

LogicManager -> SocheduleParser : parseCommand("find_event meeting")
activate SocheduleParser

create FindEventCommandParser
SocheduleParser -> FindEventCommandParser
activate FindEventCommandParser

FindEventCommandParser --> SocheduleParser
deactivate FindEventCommandParser

SocheduleParser -> FindEventCommandParser : parse("meeting")
activate FindEventCommandParser

create FindEventCommand
FindEventCommandParser -> FindEventCommand
activate FindEventCommand

FindEventCommand --> FindEventCommandParser : s
deactivate FindEventCommand

FindEventCommandParser --> SocheduleParser : s
deactivate FindEventCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindEventCommandParser -[hidden]-> SocheduleParser
destroy FindEventCommandParser

SocheduleParser --> LogicManager : s
deactivate SocheduleParser

LogicManager -> FindEventCommand : execute()
activate FindEventCommand

FindEventCommand -> Model : updateFilteredEventList(Predicate<Event> predicate)
activate Model

Model --> FindEventCommand
deactivate Model

create CommandResult
FindEventCommand -> CommandResult
activate CommandResult

CommandResult --> FindEventCommand
deactivate CommandResult

FindEventCommand --> LogicManager : result
deactivate FindEventCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindEventCommand -[hidden]->[
destroy FindEventCommand

[<--LogicManager
deactivate LogicManager
@enduml
