@startuml

start
:User executes find command;

if () then ([missing keyword])
stop
else ([valid keyword])
:Find CommandParser processes to reveal search results;
endif

if () then ([found results])
:display search results;
else ([no found results])
:show zero entities found;
endif

:Returns Find Command;

stop

@enduml
