@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TimesForWheelsParser" as TimesForWheelsParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "d:FindCommand" as FindCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find Alex")
activate LogicManager

LogicManager -> TimesForWheelsParser : parseCommand("find Alex")
activate TimesForWheelsParser

create FindCommandParser
TimesForWheelsParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> TimesForWheelsParser
deactivate FindCommandParser

TimesForWheelsParser -> FindCommandParser : parse("find Alex")
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand --> FindCommandParser : d
deactivate FindCommand

FindCommandParser --> TimesForWheelsParser : d
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> TimesForWheelsParser
destroy FindCommandParser

TimesForWheelsParser --> LogicManager : d
deactivate TimesForWheelsParser

LogicManager -> FindCommand : execute()
activate FindCommand

FindCommand -> Model : findPerson("Alex")
activate Model

Model --> FindCommand
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand
deactivate CommandResult

FindCommand --> LogicManager : result
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
