@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SocheduleParser" as SocheduleParser LOGIC_COLOR
participant ":FindTaskCommandParser" as FindTaskCommandParser LOGIC_COLOR
participant "d:FindTaskCommand" as FindTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find_task hw1")
activate LogicManager

LogicManager -> SocheduleParser : parseCommand("find_task hw1")
activate SocheduleParser

create FindTaskCommandParser
SocheduleParser -> FindTaskCommandParser
activate FindTaskCommandParser

FindTaskCommandParser --> SocheduleParser
deactivate FindTaskCommandParser

SocheduleParser -> FindTaskCommandParser : parse("hw1")
activate FindTaskCommandParser

create FindTaskCommand
FindTaskCommandParser -> FindTaskCommand
activate FindTaskCommand

FindTaskCommand --> FindTaskCommandParser : s
deactivate FindTaskCommand

FindTaskCommandParser --> SocheduleParser : s
deactivate FindTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindTaskCommandParser -[hidden]-> SocheduleParser
destroy FindTaskCommandParser

SocheduleParser --> LogicManager : s
deactivate SocheduleParser

LogicManager -> FindTaskCommand : execute()
activate FindTaskCommand

FindTaskCommand -> Model : updateFilteredTaskList(Predicate<Task> predicate)
activate Model

Model --> FindTaskCommand
deactivate Model

create CommandResult
FindTaskCommand -> CommandResult
activate CommandResult

CommandResult --> FindTaskCommand
deactivate CommandResult

FindTaskCommand --> LogicManager : result
deactivate FindTaskCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindTaskCommand -[hidden]->[
destroy FindTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
