@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

WeeblingoBook *-right-> "1" UniqueFlashcardList

UniqueFlashcardList o-right-> Flashcard

Flashcard -up-> "*" Tag

Flashcard *--> Question
Flashcard *--> Answer

@enduml
