@startuml
'https://plantuml.com/class-diagram
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #73c8df
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor #FFFFFF
skinparam ArrowColor MODEL_COLOR
show members

class Food {
  name : String
  carbos : double
  fats : double
  proteins : double
  kilocalories : double
}

@enduml
