@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes "free" and specifies interval;
if () then ([free])
    :GUI shows free message to user;
else ([not free])
    :GUI shows entries occupying interval;
endif
stop

@enduml
