@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TeachingAssistantParser" as TeachingAssistantParser LOGIC_COLOR
participant ":FreeCommandParser" as FreeCommandParser LOGIC_COLOR
participant "c:FreeCommand" as FreeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

autoactivate on
[-> LogicManager : execute("free")
LogicManager -> TeachingAssistantParser : parseCommand("free")

create FreeCommandParser
TeachingAssistantParser -> FreeCommandParser
return

TeachingAssistantParser -> FreeCommandParser : parse(start, end)

create FreeCommand
FreeCommandParser -> FreeCommand
return
FreeCommandParser --> TeachingAssistantParser
TeachingAssistantParser --> LogicManager : c
destroy FreeCommandParser

LogicManager -> FreeCommand : execute()
FreeCommand -> Model : updateFilteredEntryList(predicate)
return

create CommandResult
FreeCommand -> CommandResult
return
FreeCommand --> LogicManager : result

[<-- LogicManager

@enduml
