@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

GradeBook *-right-> "1" GradeList

GradeList o-right-> Grade

Grade *--> SubjectName
Grade *--> GradedItem
Grade *--> GradeEnum
@enduml