@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StoreMandoParser" as StoreMandoParser LOGIC_COLOR
participant "command:HelpCommand" as HelpCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("help")
activate LogicManager

LogicManager -> StoreMandoParser : parseCommand("help")
activate StoreMandoParser

create HelpCommand
StoreMandoParser -> HelpCommand
activate HelpCommand

HelpCommand --> StoreMandoParser : command
deactivate HelpCommand

StoreMandoParser --> LogicManager : command
deactivate StoreMandoParser

LogicManager -> HelpCommand : execute()
activate HelpCommand

create CommandResult
HelpCommand -> CommandResult
activate CommandResult

CommandResult --> HelpCommand : result
deactivate CommandResult

HelpCommand --> LogicManager : result
deactivate HelpCommand

[<--LogicManager : result
deactivate LogicManager

@enduml
