@startuml
!include style.puml

box Logic LOGIC_COLOR_T1

participant "e:EditOwnerCommand" as EditOwnerCommand LOGIC_COLOR
participant "imp:IdMatchPredicate" as IdMatchPredicate LOGIC_COLOR
participant "cr:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> EditOwnerCommand : execute()

activate EditOwnerCommand

EditOwnerCommand -> Model : create edited entity
activate Model
Model --> EditOwnerCommand
deactivate Model

create IdMatchPredicate
EditOwnerCommand -> IdMatchPredicate
activate IdMatchPredicate
IdMatchPredicate --> EditOwnerCommand
deactivate IdMatchPredicate

EditOwnerCommand -> Model : updateFilteredEntityList(imp)
activate Model
Model --> EditOwnerCommand
deactivate Model

create CommandResult
EditOwnerCommand -> CommandResult
activate CommandResult
CommandResult --> EditOwnerCommand
deactivate CommandResult

[<-- EditOwnerCommand : cr
deactivate EditOwnerCommand

@enduml
