@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


FlashcardBook --> "1" UniqueScoreHistoryList
UniqueScoreHistoryList --> "*" Score
@enduml
