@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WeeblingoParser" as WeeblingoParser LOGIC_COLOR
participant ":LearnCommandParser" as LearnCommandParser LOGIC_COLOR
participant "l:LearnCommand" as LearnCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("learn t/hiragana")
activate LogicManager

LogicManager -> WeeblingoParser : parseCommand("learn t/hiragana")
activate WeeblingoParser

create LearnCommandParser
WeeblingoParser -> LearnCommandParser :
activate LearnCommandParser

LearnCommandParser --> WeeblingoParser :
deactivate LearnCommandParser

WeeblingoParser --> LearnCommandParser : parse("t/hiragana")
activate LearnCommandParser

create LearnCommand
LearnCommandParser -> LearnCommand :
activate LearnCommand

LearnCommand --> LearnCommandParser : l
deactivate LearnCommand

LearnCommandParser --> WeeblingoParser : l
deactivate LearnCommandParser

LearnCommandParser -[hidden]-> WeeblingoParser
destroy LearnCommandParser

WeeblingoParser --> LogicManager : l
deactivate WeeblingoParser

LogicManager -> LearnCommand : execute(model)
activate LearnCommand

LearnCommand -> Model : updateFilteredFlashcardList(\nflashcard -> flashcard.checkHasTags(hiragana))
activate Model

Model --> LearnCommand
deactivate Model

create CommandResult
LearnCommand -> CommandResult
activate CommandResult

CommandResult --> LearnCommand
deactivate CommandResult

LearnCommand --> LogicManager : result
deactivate LearnCommand

[<--LogicManager
deactivate LogicManager
@enduml
