@startuml
'https://plantuml.com/activity-diagram-beta

start
:User inputs a levelup command;
:Command parsed by AddressBookParser;

if () then ([command word is valid])
    :Argument parsed by LevelUpCommandParser;
    if () then ([argument is valid])
        :Returns LevelUpCommand with indexes to be excluded as argument;
        :Model filters the excluded people then advances the rest of the people in the
        transformed persons list by one education level;
        :Displays transformed persons list;
    else ([else])
        :ParseException is thrown;
    endif
else ([else])
    :ParseException is thrown;
endif

stop

@enduml
