@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SocheduleParser" as SocheduleParser LOGIC_COLOR
participant "s:ListTaskCommand" as ListTaskCommand LOGIC_COLOR
participant "CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : parse("list_task")
activate LogicManager

LogicManager -> SocheduleParser : parseCommand("list_task")
activate SocheduleParser

create ListTaskCommand
SocheduleParser -> ListTaskCommand
activate ListTaskCommand

ListTaskCommand --> SocheduleParser : s
deactivate ListTaskCommand

LogicManager <-- SocheduleParser : s
deactivate SocheduleParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SocheduleParser -[hidden]->[

LogicManager -> ListTaskCommand : execute()
activate ListTaskCommand

ListTaskCommand -> Model : updateFilteredList(Predicate<Task> predicate)
activate Model
ListTaskCommand <-- Model
deactivate Model

create CommandResult
ListTaskCommand -> CommandResult
activate CommandResult
ListTaskCommand <-- CommandResult
deactivate CommandResult

LogicManager <-- ListTaskCommand
deactivate ListTaskCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListTaskCommand -[hidden]->[
destroy ListTaskCommand

[<-- LogicManager : CommandResult
@enduml
