@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DeliveryListParser" as DeliveryListParser LOGIC_COLOR
participant "command:ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list")
activate LogicManager

LogicManager -> DeliveryListParser : parseCommand("list")
activate DeliveryListParser

create ListCommand
DeliveryListParser -> ListCommand
activate ListCommand

ListCommand --> DeliveryListParser : command
deactivate ListCommand

DeliveryListParser --> LogicManager : command
deactivate DeliveryListParser

LogicManager -> ListCommand : execute()
activate ListCommand

ListCommand -> Model : updateFilteredCustomerList()
activate Model

Model --> ListCommand
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand

[<--LogicManager
deactivate LogicManager
@enduml
