@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TeachingAssistantParser" as TeachingAssistantParser LOGIC_COLOR
participant ":ListEntryFormatPredicate" as ListEntryFormatPredicate LOGIC_COLOR
participant ":ListEntryCommand" as ListEntryCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("elist day")
activate LogicManager

LogicManager -> TeachingAssistantParser : parseCommand("elist day")
activate TeachingAssistantParser

create ListEntryFormatPredicate
TeachingAssistantParser -> ListEntryFormatPredicate
activate ListEntryFormatPredicate

ListEntryFormatPredicate --> TeachingAssistantParser
deactivate ListEntryFormatPredicate

create ListEntryCommand
TeachingAssistantParser -> ListEntryCommand
activate ListEntryCommand

ListEntryCommand --> TeachingAssistantParser
deactivate ListEntryCommand

TeachingAssistantParser --> LogicManager : command
deactivate TeachingAssistantParser

LogicManager-> ListEntryCommand : execute()
activate ListEntryCommand

ListEntryCommand -> Model : updateFilteredEntryList(predicate)
activate Model

Model --> ListEntryCommand
deactivate Model

create CommandResult
ListEntryCommand -> CommandResult
activate CommandResult

CommandResult --> ListEntryCommand
deactivate CommandResult

ListEntryCommand --> LogicManager : commandResult
deactivate ListEntryCommand

[<--LogicManager
deactivate LogicManager
@enduml
