@startuml
start
:User enters list command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([user input is valid])
    :Parse user input;
    :Update current predicate in Model;
    :Update filtered item list in Model;
    :Display filtered list;
    :Display command success message;
else ([else])
    :Display parse error message;
endif
stop
@enduml
