@startuml
!include style.puml

box UI UI_COLOR_T2
participant ":MainWindow" as MainWindow UI_COLOR
participant ":ImportantDatesWindow" as ImportantDatesWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

[-> MainWindow : executeCommand(list-date)
activate MainWindow

MainWindow -> LogicManager : execute(list-date)
activate LogicManager

ref over LogicManager, ModelManager : list important date command

LogicManager --> MainWindow
deactivate LogicManager

MainWindow -> MainWindow : handleImportantDates()
activate MainWindow

MainWindow -> ImportantDatesWindow : show()
activate ImportantDatesWindow

ImportantDatesWindow -> LogicManager : getTransformedImportantDatesList()
activate LogicManager

LogicManager -> ModelManager : getTransformedImportantDatesList()
activate ModelManager

ModelManager --> LogicManager
deactivate ModelManager

LogicManager --> ImportantDatesWindow
deactivate LogicManager

ImportantDatesWindow --> MainWindow
deactivate

MainWindow --> MainWindow
deactivate MainWindow


[<--MainWindow
deactivate MainWindow
@enduml