@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

package Parser {
Interface Parser <<Interface>>
Class BookingSystemParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

package Command {
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
}

package CommandState {
Class CommandState
Class XYZCommandState
}

package Intermediate {
Interface Intermediate <<Interface>>
Class XYZIntermediate
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
LogicManager -->"1" BookingSystemParser
BookingSystemParser .left.> XYZCommandParser: creates >

XYZCommandParser ..> XYZCommand : creates >
XYZCommandParser ..|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix
XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

XYZCommandState -up-|> CommandState
CommandState *--> "1" Model

XYZIntermediate ..|> Intermediate
XYZIntermediate *--> XYZCommandState
Intermediate ..> CommandState
XYZCommand ..> XYZCommandState : creates >
note right of XYZCommandState: XYZCommand = AddCommand, \nFindCommand, etc

LogicManager --> Model
Command .right.> Model
note left of XYZCommand: XYZCommandState = AddBookingCommandState, \nAddPersonCommandState, etc.

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult
CommandResult -[hidden]-> Parser
@enduml
