@startuml
!include Style.puml


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "m:MassBlacklistCommand" as MassBlacklistCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR_T2
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR_T2
end box


 -> LogicManager : execute("massblist 2-5...")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("massblist 2-5...")
activate AddressBookParser

create MassBlacklistCommand
AddressBookParser -> MassBlacklistCommand :
activate MassBlacklistCommand

MassBlacklistCommand --> AddressBookParser :
deactivate MassBlacklistCommand

AddressBookParser --> LogicManager : m
deactivate AddressBookParser

LogicManager -> MassBlacklistCommand : execute()
activate MassBlacklistCommand

MassBlacklistCommand -> Model : massBlacklist(2,5)
activate Model

Model --> MassBlacklistCommand :
deactivate Model
MassBlacklistCommand --> LogicManager : result
deactivate MassBlacklistCommand
MassBlacklistCommand -[hidden]-> LogicManager : result
destroy MassBlacklistCommand


LogicManager -> Storage : saveAddressBook(addressBook)
activate Storage

Storage -> Storage : Save to file
activate Storage

Storage --> Storage
deactivate Storage


Storage --> LogicManager :
deactivate Storage

<-- LogicManager

@enduml
