@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClientBookParser" as ClientBookParser LOGIC_COLOR
participant ":MeetCommandParser" as MeetCommandParser LOGIC_COLOR
participant "m:MeetCommand" as MeetCommand LOGIC_COLOR
participant "p:Person" as Person LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
end box

[-> LogicManager : execute("meet 1 -add 20.06.2021 12:00 15:00 MRT")
activate LogicManager

LogicManager -> ClientBookParser : parseCommand("meet 1 -add 20.06.2021 12:00 15:00 MRT")
activate ClientBookParser

create MeetCommandParser
ClientBookParser -> MeetCommandParser
activate MeetCommandParser

MeetCommandParser --> ClientBookParser
deactivate MeetCommandParser

ClientBookParser -> MeetCommandParser : parse("1 -add 20.06.2021 12:00 15:00 MRT")
activate MeetCommandParser

create MeetCommand
MeetCommandParser -> MeetCommand
activate MeetCommand

MeetCommand --> MeetCommandParser : m
deactivate MeetCommand

MeetCommandParser --> ClientBookParser : m
deactivate MeetCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
MeetCommand -[hidden]-> ClientBookParser
destroy MeetCommandParser

ClientBookParser --> LogicManager : m
deactivate ClientBookParser

LogicManager -> MeetCommand : execute()
activate MeetCommand

create Person
MeetCommand -> Person : addMeeting(personToMeet, meeting)
activate Person

Person --> MeetCommand :newPerson
deactivate Person

MeetCommand -> Model : setPerson(p)
activate Model

Model -> AddressBook : setPerson(personToMeet, newPerson)
activate AddressBook

AddressBook --> Model
deactivate AddressBook

Model --> MeetCommand
deactivate Model

create CommandResult
MeetCommand -> CommandResult
activate CommandResult

CommandResult --> MeetCommand
deactivate CommandResult

MeetCommand --> LogicManager : result
deactivate MeetCommand

[<--LogicManager
deactivate LogicManager
@enduml
