@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Person {
Class Person
Class Address
Class Email
Class Name
Class Phone
Class UniquePersonList
}

Package Meeting {
Class Meeting
Class UniqueMeetingList
Class Entry
}


Package Tag {
Class Tag
}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag
Person *--> "0...1" Meeting

AddressBook *--> "1" UniqueMeetingList
UniqueMeetingList o--> "*" Entry
Entry --> "key" Meeting
Entry --> "value" Person

UniqueMeetingList -[hidden]down-> Entry
UniqueMeetingList -[hidden]left-> UniquePersonList

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Tag -[hidden]left-> Meeting
Entry -[hidden]left-> Person

ModelManager ----->" ~* filtered list" Person
@enduml
