@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Person {
Class Passenger
Class Driver
}

Passenger "*" -> "0..1" Driver

@enduml