@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<Interface>>\nReadOnlyPropertyBook" as ReadOnlyPropertyBook
Class "<<Interface>>\nReadOnlyAppointmentBook" as ReadOnlyAppointmentBook
Class "<<Interface>>\nModel" as Model
Class "<<Interface>>\nObservableList" as ObservableList
Class PropertyBook
Class AppointmentBook
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Property as PropertyPackage{
Class Property
Class UniquePropertyList
Class HiddenModel1 #FFFFFF
}

Package Appointment as AppointmentPackage{
Class Appointment
Class UniqueAppointmentList
Class HiddenModel2 #FFFFFF
Class HiddenModel3 #FFFFFF
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

HiddenModel2 .left[hidden].> UniqueAppointmentList

Model .right.> ObservableList
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager .up.|> Model
ModelManager o-left-> "1" UserPrefs
ModelManager o--> "1" PropertyBook
ModelManager o--> "1" AppointmentBook

PropertyBook .left.|> ReadOnlyPropertyBook
AppointmentBook .right.|> ReadOnlyAppointmentBook

PropertyBook *--> "1 " UniquePropertyList
AppointmentBook *--> "1  " UniqueAppointmentList

UniquePropertyList o-left-> "*" Property
UniqueAppointmentList o-left-> "*" Appointment

ModelManager ----> "filtered list *" Property
ModelManager ----> "filtered list *" Appointment

AppointmentPackage -left[hidden]- PropertyPackage

@enduml
