@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TutorTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class Appointment

Package Tutor {
Class Tutor
Class Address
Class Email
Class Name
Class Phone
}

Package Tag {
Class Tag
}

Package Appointment {
Class Appointment
Class Email
Class Subject
Class DateTime
Class Day
Class Location
}

Package Appointment {
Class Appointment
Class Email
Class AppointmentSubject
Class DateTime
Class Day
Class Location
}

Package List {
Class List
Class TutorList
Class AppointmentList
Class TagList
}

Package Subject {
Class Subject
Class SubjectName
Class HourlyRate
Class EducationLevel
Class YearsOfExperience
Class Qualifications
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" TutorTracker
ModelManager o-left->  UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

List *--> "1" TutorList
List *--> "1" AppointmentList
List *--> "1" TagList

Appointment *--> "1" AppointmentSubject
Appointment *--> "1" DateTime
Appointment *--> "1" Day
Appointment *--> "1" Location

TutorTracker *--> "*" Tutor
TutorTracker *--> "*" Appointment
TutorTracker *--> List

Tutor *--> "1" Name
Tutor  *--> "1" Phone
Tutor  *--> "1" Email
Tutor  *--> "1" Address
Tutor  *--> "*" Tag
Tutor  --> "*" Subject

Subject *--> "*" SubjectName
Subject *--> "*" HourlyRate
Subject *--> "*" EducationLevel
Subject *--> "*" YearsOfExperience
Subject *--> "*" Qualifications

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

@enduml
