@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SocheduleParser" as SocheduleParser LOGIC_COLOR
participant ":PinTaskCommandParser" as PinTaskCommandParser LOGIC_COLOR
participant "p:PinTaskCommand" as PinTaskCommand LOGIC_COLOR
participant "CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : parse("pin_task 1")
activate LogicManager

LogicManager -> SocheduleParser : parseCommand("pin_task 1")
activate SocheduleParser

create PinTaskCommandParser
SocheduleParser -> PinTaskCommandParser
activate PinTaskCommandParser
SocheduleParser <-- PinTaskCommandParser
deactivate PinTaskCommandParser

SocheduleParser -> PinTaskCommandParser: parse("1")
activate PinTaskCommandParser

create PinTaskCommand
PinTaskCommandParser -> PinTaskCommand
activate PinTaskCommand
PinTaskCommandParser <--PinTaskCommand : p
deactivate PinTaskCommand

SocheduleParser <--PinTaskCommandParser : p
deactivate PinTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
PinTaskCommandParser -[hidden]->[
destroy PinTaskCommandParser

LogicManager <-- SocheduleParser : p
deactivate SocheduleParser

LogicManager -> PinTaskCommand : execute()
activate PinTaskCommand

PinTaskCommand -> Model : pinTask()
activate Model
PinTaskCommand <-- Model
deactivate Model

PinTaskCommand -> Model : sortTaskDefault()
activate Model
PinTaskCommand <-- Model
deactivate Model

create CommandResult
PinTaskCommand -> CommandResult
activate CommandResult
PinTaskCommand <-- CommandResult
deactivate CommandResult

LogicManager <-- PinTaskCommand : CommandResult
deactivate PinTaskCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
PinTaskCommand -[hidden]->[
destroy PinTaskCommand

[<-- LogicManager : CommandResult
@enduml
