@startuml
!include style.puml

actor User
participant "plan:Plan" as Plan UI_COLOR
participant "tags:Set<Tag>" as Tags LOGIC_COLOR

create Plan
User -> Plan : new Plan(description, tags, semesters)
activate Plan

Plan -> Tags : addAll(tags)
activate Tags

Plan <-- Tags
deactivate Tags

Plan -> Plan : countModules()
activate Plan

Plan --> Plan
deactivate Plan

User <-- Plan
deactivate Plan
[<-- User
@enduml
