@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class ProgressCalculator
class FoodIntakeList
class DietPlan
class User
class FoodIntake
class PlanInfoCalculator
class MacroNutrientsComposition
class Bmi
class Gender
class Age

PlanInfoCalculator ..> Bmi
PlanInfoCalculator ..> Gender
PlanInfoCalculator ..> Age

class PlanInfoCalculator {
calories : double
carbohydrates : double
proteins : double
fats : double
PlanInfoCalculator(User, DietPlan)
}

PlanInfoCalculator ..> MacroNutrientsComposition
PlanInfoCalculator ..> User
PlanInfoCalculator ..> DietPlan

class MacroNutrientsComposition {
carbohydrates : double
fats : double
proteins : double
}

class ProgressCalculator {
{static}calculateProgress(FoodIntakeList, DietPlan, User)
}

ProgressCalculator ..> FoodIntakeList
ProgressCalculator ..> DietPlan
ProgressCalculator ..> User
ProgressCalculator ..> PlanInfoCalculator
ProgressCalculator ..> FoodIntake

enum PlanType {
WEIGHT_GAIN
WEIGHT_LOSS
WEIGHT_MAINTAIN
}

@enduml
