@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Receiving the input Add command


class Logic as "__logic:LogicManager__"

class Command as "__command:Command__"

class AddressBookParser as "__addressBookParser:AddressBookParser__"

class AddCommandParser as "__:AddCommandParser__"
Logic -down- Command
Command -down- AddressBookParser
AddressBookParser -right- AddCommandParser
@end
