@startuml
start
:User executes Remark command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (Index found) then ([Delivery task exists])
        :Add new Remark to Delivery Task;
else ([else])
    : Show error message;
endif
stop
@enduml
