@startuml
start
:User executes send 1 command;
:Retrieve first endpoint;
:Construct an EndpointCaller;
:Call endpoint and construct a GET request;
:Send and execute request;
:Receive and display response;

stop
@enduml
