@startuml
start
:User executes send command;
:Retrieve endpoint with given index;
:Construct an EndpointCaller;
:Call endpoint and construct a GET request;
:Send and execute request;
:Receive and display response;

stop
@enduml
