@startuml
!include style.puml

box BudgetBabyCommandParser LOGIC_COLOR_T1
participant ":BudgetBabyCommand" as BudgetBabyCommand LOGIC_COLOR
participant ":BudgetBabyParser" as BudgetBabyParser LOGIC_COLOR
participant ":ResetFilterCommandParser" as ResetFilterCommandParser LOGIC_COLOR
participant "c:ResetFilterCommand" as ResetFilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box BudgetBabyModel MODEL_COLOR_T1
participant ":BudgetBabyModel" as Model MODEL_COLOR
end box

[-> BudgetBabyCommand : execute(model)
activate BudgetBabyCommand

BudgetBabyCommand -> BudgetBabyParser : parseCommand("reset-filter")
activate BudgetBabyParser

create ResetFilterCommandParser
BudgetBabyParser -> ResetFilterCommandParser
activate ResetFilterCommandParser

ResetFilterCommandParser --> BudgetBabyParser
deactivate ResetFilterCommandParser

BudgetBabyParser -> ResetFilterCommandParser : parse("reset-filter")
activate ResetFilterCommandParser

create ResetFilterCommand
ResetFilterCommandParser -> ResetFilterCommand
activate ResetFilterCommand

ResetFilterCommand --> ResetFilterCommandParser : c
deactivate ResetFilterCommand

ResetFilterCommandParser --> BudgetBabyParser : c
deactivate ResetFilterCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ResetFilterCommandParser -[hidden]-> BudgetBabyParser
destroy ResetFilterCommandParser

BudgetBabyParser --> BudgetBabyCommand : c
deactivate BudgetBabyParser

BudgetBabyCommand -> ResetFilterCommand : execute()
activate ResetFilterCommand

ResetFilterCommand -> Model : resetFilter()
activate Model

Model --> ResetFilterCommand
deactivate Model

create CommandResult
ResetFilterCommand -> CommandResult
activate CommandResult

CommandResult --> ResetFilterCommand
deactivate CommandResult

ResetFilterCommand --> BudgetBabyCommand : result
deactivate ResetFilterCommand

[<--BudgetBabyCommand
deactivate BudgetBabyCommand
@enduml
