@startuml
'https://plantuml.com/activity-diagram-beta

start
:Check if Room exists;
if () then ([Room exists])
    :Check if Resident exists;
    if () then ([Resident exists])
        : Check if Resident or Room is already allocated;
        if () then ([None allocated])
            : Set the room number in Resident;
            : Set the occupancy as 'Y' in Room;
            stop
        else ([Resident or/and Room is allocated])
            stop
    endif
    else ([Resident does not exist])
        stop
   endif

else ([Room does not exist])
    stop
@enduml
