@startuml
start
:User inputs 'return bc/1000000000';

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid input])
    :execute command;
    :markRecordAsReturned;
    :changeReaderStatus;
    :changeBookStatus;
    :return book success;
else ([input invalid or check condition failed])
    :command invalid;
endif
stop
@enduml
