@startuml
start
:User executes run command;
:Parse command arguments;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([quick run syntax])
    :Retrieve URL;
    :Construct endpoint
    for a GET request;
else ([else])
    :Retrieve request details;
    :Construct endpoint
    as specified;
endif
:Create run command
with the endpoint;
:Call endpoint;
:Display response;

stop
@enduml