@startuml
start
:User executes run command;
:Parse command arguments;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([quick run syntax])
    :Retrieve URL and
    construct a GET request;
    :Send request;
    :Display response;
else ([else])
    :Construct endpoint
    as specified;
    :Send request;
    :Display response;
endif
stop
@enduml
