@startuml
!include style.puml

box UI UI_COLOR_T2
participant ":MainWindow" as MainWindow UI_COLOR
participant ":ScheduleWindow" as ScheduleWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "s:ScheduleCommand" as ScheduleCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

[-> MainWindow : executeCommand(schedule)
activate MainWindow

MainWindow -> LogicManager : execute(schedule)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(schedule)
activate AddressBookParser

create ScheduleCommand
AddressBookParser -> ScheduleCommand
activate ScheduleCommand

ScheduleCommand --> AddressBookParser
deactivate ScheduleCommand
ScheduleCommand -[hidden]-> AddressBookParser
destroy ScheduleCommand

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> ScheduleCommand : execute()
activate ScheduleCommand

ScheduleCommand -> ModelManager : updateFilteredLessonList()
activate ModelManager

ModelManager --> ScheduleCommand
deactivate ModelManager

ScheduleCommand --> LogicManager
deactivate ScheduleCommand

LogicManager --> MainWindow
deactivate LogicManager

MainWindow -> MainWindow : handleSchedule()
activate MainWindow

MainWindow -> ScheduleWindow : show()
activate ScheduleWindow

ScheduleWindow -> LogicManager : getEachDayLesson()
activate LogicManager

LogicManager -> ModelManager
activate ModelManager

ModelManager --> LogicManager
deactivate ModelManager

LogicManager --> ScheduleWindow
deactivate LogicManager

ScheduleWindow --> MainWindow
deactivate

MainWindow --> MainWindow
deactivate MainWindow


[<--MainWindow
deactivate MainWindow
@enduml
