@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ScheduleCommandParser" as ScheduleCommandParser LOGIC_COLOR
participant "s:ScheduleCommand" as ScheduleCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("schedule 1 ...")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("schedule 1 ...")
activate AddressBookParser

create ScheduleCommandParser
AddressBookParser -> ScheduleCommandParser
activate ScheduleCommandParser

ScheduleCommandParser --> AddressBookParser
deactivate ScheduleCommandParser

AddressBookParser -> ScheduleCommandParser : parse("1 ...")
activate ScheduleCommandParser

create ScheduleCommand
ScheduleCommandParser -> ScheduleCommand
activate ScheduleCommand

ScheduleCommand --> ScheduleCommandParser : s
deactivate ScheduleCommand

ScheduleCommandParser --> AddressBookParser : s
deactivate ScheduleCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ScheduleCommandParser -[hidden]-> AddressBookParser
destroy ScheduleCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> ScheduleCommand : execute()
activate ScheduleCommand

ScheduleCommand -> Model : SchedulePerson(1 ...)
activate Model

Model --> ScheduleCommand
deactivate Model

create CommandResult
ScheduleCommand -> CommandResult
activate CommandResult

CommandResult --> ScheduleCommand
deactivate CommandResult

ScheduleCommand --> LogicManager : result
deactivate ScheduleCommand

[<--LogicManager
deactivate LogicManager
@enduml
