@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ImposterParser" as ImposterParser LOGIC_COLOR
participant "s:SendCommand" as SendCommand LOGIC_COLOR
participant ":EndpointCaller" as EndpointCaller ENDPOINTCALLER_COLOR

end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("send 1")
activate LogicManager

LogicManager -> ImposterParser : parseCommand("send 1")
activate ImposterParser

create SendCommand
ImposterParser -> SendCommand
activate SendCommand

SendCommand --> ImposterParser
deactivate SendCommand

ImposterParser --> LogicManager : u
deactivate ImposterParser

LogicManager -> SendCommand : execute()
activate SendCommand

SendCommand -> Model : getEndpointAtIndex()
activate Model

Model --> SendCommand
deactivate Model

create EndpointCaller
SendCommand -> EndpointCaller : new
activate EndpointCaller

return

SendCommand -[ENDPOINTCALLER_COLOR]--> EndpointCaller : callEndpoint()
activate EndpointCaller

return response
deactivate EndpointCaller ENDPOINTCALLER_COLOR
destroy EndpointCaller

SendCommand --> LogicManager : result
deactivate SendCommand
SendCommand -[hidden]-> LogicManager : result
destroy SendCommand

[<--LogicManager
deactivate LogicManager
@enduml
