@startuml
!include style.puml

box BudgetBabyLogic LOGIC_COLOR_T1
participant ":BudgetBabyLogicManager" as BudgetBabyLogicManager LOGIC_COLOR
participant ":BudgetBabyParser" as BudgetBabyParser LOGIC_COLOR
participant ":SetBudgetCommandParser" as SetBudgetCommandParser LOGIC_COLOR
participant "c:SetBudgetCommand" as SetBudgetCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box BudgetBabyModel MODEL_COLOR_T1
participant ":BudgetBabyModel" as Model MODEL_COLOR
end box

[-> BudgetBabyLogicManager : execute("set-bg 1000")
activate BudgetBabyLogicManager

BudgetBabyLogicManager -> BudgetBabyParser : parseCommand("set-bg 1000")
activate BudgetBabyParser

create SetBudgetCommandParser
BudgetBabyParser -> SetBudgetCommandParser
activate SetBudgetCommandParser

SetBudgetCommandParser --> BudgetBabyParser
deactivate SetBudgetCommandParser

BudgetBabyParser -> SetBudgetCommandParser : parse("set-bg 1000")
activate SetBudgetCommandParser

create SetBudgetCommand
SetBudgetCommandParser -> SetBudgetCommand
activate SetBudgetCommand

SetBudgetCommand --> SetBudgetCommandParser : c
deactivate SetBudgetCommand

SetBudgetCommandParser --> BudgetBabyParser : c
deactivate SetBudgetCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SetBudgetCommandParser -[hidden]-> BudgetBabyParser
destroy SetBudgetCommandParser

BudgetBabyParser --> BudgetBabyLogicManager : c
deactivate BudgetBabyParser

BudgetBabyLogicManager -> SetBudgetCommand : execute()
activate SetBudgetCommand

SetBudgetCommand -> Model : setBudget(budget)
activate Model

Model --> SetBudgetCommand
deactivate Model

create CommandResult
SetBudgetCommand -> CommandResult
activate CommandResult

CommandResult --> SetBudgetCommand
deactivate CommandResult

SetBudgetCommand --> BudgetBabyLogicManager : result
deactivate SetBudgetCommand

[<--BudgetBabyLogicManager
deactivate BudgetBabyLogicManager
@enduml
