@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes Sort command;
if () then ([user input is valid])
    :Sort current delivery list;
    :Show sorted delivery list;
else ([else])
    :Show unknown command message;
endif
stop
@enduml
