@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PlannerParser" as PlannerParser LOGIC_COLOR
participant ":SortCommandParser" as SortCommandParser LOGIC_COLOR
participant ":SortCommand" as SortCommand LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(args)
activate LogicManager

LogicManager -> PlannerParser : parseCommand(args)
activate PlannerParser

create SortCommandParser
PlannerParser -> SortCommandParser : new SortCommandParser()
activate SortCommandParser

SortCommandParser --> PlannerParser : return
deactivate SortCommandParser

PlannerParser -> SortCommandParser : parse(args)
activate SortCommandParser

create SortCommand
SortCommandParser -> SortCommand : new SortCommand(comparator, true)
activate SortCommand

SortCommand --> SortCommandParser : command
deactivate SortCommand

SortCommandParser --> PlannerParser : command
deactivate SortCommandParser

PlannerParser --> LogicManager : command
deactivate PlannerParser

LogicManager -> SortCommand : execute(model)
activate SortCommand

SortCommand -> Model : updateSortedTaskList(comparator)
activate Model

SortCommand --> LogicManager : result
deactivate SortCommand

SortCommand -[hidden]-> LogicManager : result
destroy SortCommand

[<--LogicManager : return
deactivate LogicManager
@enduml
