@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StoreMandoParser" as StoreMandoParser LOGIC_COLOR
participant ":SortCommandParser" as SortCommandParser LOGIC_COLOR
participant "command:SortAscendingQuantityCommand" as SortAscendingQuantityCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "comparator:ItemComparatorByIncreasingQuantity" as ItemComparatorByIncreasingQuantity MODEL_COLOR
end box

[-> LogicManager : execute("sort quantity asc")
activate LogicManager

LogicManager -> StoreMandoParser : parseCommand("sort quantity asc")
activate StoreMandoParser

create SortCommandParser
StoreMandoParser -> SortCommandParser
activate SortCommandParser

SortCommandParser --> StoreMandoParser
deactivate SortCommandParser

StoreMandoParser -> SortCommandParser : parse("quantity asc")
activate SortCommandParser

create SortAscendingQuantityCommand
SortCommandParser -> SortAscendingQuantityCommand : SortAscendingQuantityCommand()
activate SortAscendingQuantityCommand
SortAscendingQuantityCommand --> SortCommandParser : command
deactivate SortAscendingQuantityCommand

SortCommandParser --> StoreMandoParser : command
deactivate SortCommandParser

SortCommandParser -[hidden]-> StoreMandoParser
destroy SortCommandParser

StoreMandoParser --> LogicManager : command
deactivate StoreMandoParser


LogicManager -> SortAscendingQuantityCommand : execute(model)
activate SortAscendingQuantityCommand

SortAscendingQuantityCommand -> Model : getFilteredItemList()
activate Model
Model --> SortAscendingQuantityCommand
deactivate Model

create ItemComparatorByIncreasingQuantity
SortAscendingQuantityCommand -> ItemComparatorByIncreasingQuantity : ItemComparatorByIncreasingQuantity()
activate ItemComparatorByIncreasingQuantity
ItemComparatorByIncreasingQuantity --> SortAscendingQuantityCommand : comparator
deactivate ItemComparatorByIncreasingQuantity

SortAscendingQuantityCommand -> Model : updateSortedItemList(comparator)
activate Model
Model --> SortAscendingQuantityCommand
deactivate Model

SortAscendingQuantityCommand -> Model : getSortedItemList()
activate Model
Model --> SortAscendingQuantityCommand : sortedItemList
deactivate Model

SortAscendingQuantityCommand -> Model : setItems(sortedItemList)
activate Model
Model --> SortAscendingQuantityCommand
deactivate Model

create CommandResult
SortAscendingQuantityCommand -> CommandResult : CommandResult()
activate CommandResult
CommandResult --> SortAscendingQuantityCommand : result
deactivate CommandResult

SortAscendingQuantityCommand --> LogicManager : result
deactivate SortAscendingQuantityCommand

[<--LogicManager : result
deactivate LogicManager
@enduml


