@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClientBookParser" as ClientBookParser LOGIC_COLOR
participant ":SortCommandParser" as SortCommandParser LOGIC_COLOR
participant "s:SortCommand" as SortCommand LOGIC_COLOR
participant "c:Comparator" as Comparator LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sort -n -asc")
activate LogicManager

LogicManager -> ClientBookParser : parseCommand("sort -n -asc")
activate ClientBookParser

create SortCommandParser
ClientBookParser -> SortCommandParser
activate SortCommandParser

SortCommandParser --> ClientBookParser
deactivate SortCommandParser

ClientBookParser -> SortCommandParser : parse("-n -asc")
activate SortCommandParser

create SortCommand
SortCommandParser -> SortCommand
activate SortCommand

SortCommand --> SortCommandParser : s
deactivate SortCommand

SortCommandParser --> ClientBookParser : s
deactivate SortCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SortCommandParser -[hidden]-> ClientBookParser
destroy SortCommandParser

ClientBookParser --> LogicManager : s
deactivate ClientBookParser

LogicManager -> SortCommand : execute()
activate SortCommand

create Comparator
SortCommand -> Comparator
activate Comparator

Comparator --> SortCommand : c
deactivate Comparator

SortCommand -> Model : updateSortedPersonList(c)
activate Model

Model --> SortCommand
deactivate Model

create CommandResult
SortCommand -> CommandResult
activate CommandResult

CommandResult --> SortCommand
deactivate CommandResult

SortCommand --> LogicManager : result
deactivate SortCommand

[<--LogicManager
deactivate LogicManager
@enduml
