@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Status <<Rectangle>> {
    Class Status <<Interface>> {
        +next()
    }
    Class Option {
        +next()
    }
    Class SalesAgreement {
        {method} next()
    }
    Class Completion {
        +next()
    }
    Class Offer
}

Option --|> Status
SalesAgreement --|> Status
Completion --|> Status

Option *--> "1 " Offer
SalesAgreement *--> "1 " Offer
Completion *--> "1 " Offer

@enduml
