@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface TaskTrackerStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonTaskTrackerStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> TaskTrackerStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonTaskTrackerStorage .left.|> TaskTrackerStorage
JsonTaskTrackerStorage .down.> JsonSerializableTaskTracker
JsonSerializableTaskTracker .right.> JsonAdaptedTask
JsonAdaptedTask .right.> JsonAdaptedTag
@enduml
