@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AppointmentScheduleStorage <<Interface>>
Class "{abstract}\nAddressBookStorage" as AddressBookStorage
Class "{abstract}\nJsonAdaptedPerson" as JsonAdaptedPerson

Class StorageManager
Class JsonUserPrefsStorage
Class JsonPatientRecordsStorage
Class JsonDoctorRecordsStorage
Class JsonAppointmentScheduleStorage

StorageManager .left.|> Storage
StorageManager o--> UserPrefsStorage
StorageManager o--> AddressBookStorage
StorageManager o--> AppointmentScheduleStorage

UserPrefsStorage -[hidden]left- AppointmentScheduleStorage
AppointmentScheduleStorage -[hidden]left- AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPatientRecordsStorage -up-|> AddressBookStorage
JsonDoctorRecordsStorage -up-|> AddressBookStorage
JsonPatientRecordsStorage .down.> JsonSerializablePatientRecords
JsonDoctorRecordsStorage .down.> JsonSerializableDoctorRecords

JsonAdaptedPatient -right-|> JsonAdaptedPerson
JsonAdaptedDoctor -left-|> JsonAdaptedPerson

JsonSerializablePatientRecords .down.> JsonAdaptedPatient
JsonSerializableDoctorRecords .down.> JsonAdaptedDoctor
JsonAdaptedPerson .right.> JsonAdaptedTag
JsonAdaptedPatient .down.> JsonAdaptedTag
JsonAdaptedDoctor .down.> JsonAdaptedTag

AppointmentScheduleStorage <|.down. JsonAppointmentScheduleStorage
JsonAppointmentScheduleStorage .down.>JsonSerializableAppointmentSchedule
JsonSerializableAppointmentSchedule .down.> JsonAdaptedAppointment
JsonAdaptedAppointment .down.> JsonAdaptedTag

@enduml
