/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'T1 through T4 are shades of the original color from darkest to lightest

!define UI_COLOR_DARK #5CA65A
!define UI_COLOR #77DD66
!define UI_COLOR_T1 #8FE381
!define UI_COLOR_T2 #A7E99C
!define UI_COLOR_T3 #BFEEB7
!define UI_COLOR_T4 #D7F4D2

!define LOGIC_COLOR_DARK #2B40AB
!define LOGIC_COLOR #78A2CC
!define LOGIC_COLOR_T1 #88AED0
!define LOGIC_COLOR_T2 #96B9D0
!define LOGIC_COLOR_T3 #A4C3D2
!define LOGIC_COLOR_T4 #AECBD6

!define MODEL_COLOR_DARK #A84541
!define MODEL_COLOR #CF4040
!define MODEL_COLOR_T1 #FF7974
!define MODEL_COLOR_T2 #FF8986
!define MODEL_COLOR_T3 #FF9997
!define MODEL_COLOR_T4 #FFA9A9

!define STORAGE_COLOR_DARK #BF7855
!define STORAGE_COLOR #FFA071
!define STORAGE_COLOR_T1 #FFB480
!define STORAGE_COLOR_T2 #FEC98F
!define STORAGE_COLOR_T3 #FEDD9E
!define STORAGE_COLOR_T2 #FDF1AD

!define USER_COLOR #000000

scale 854*480

skinparam BackgroundColor #e3f0ff

skinparam Shadowing false

skinparam sequenceArrowThickness 2

skinparam Rectangle {
    BorderThickness 2
    BorderColor #000000
}

skinparam Class {
    FontColor #FFFFFF
    BorderThickness 2
    BorderColor #000000
    StereotypeFontColor #FFFFFF
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #FFFFFF
    FontName Arial
}

skinparam Participant {
    FontColor #FFFFFFF
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
