@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Parser <<Rectangle>>{
Interface Parser <<interface>>
TagCommandParser .up.|> Parser
AddTagCommandParser .up.|> Parser
DeleteTagCommandParser .up.|> Parser
}
@enduml
