@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SocheduleParser" as SocheduleParser LOGIC_COLOR
participant "s:TodayTaskCommand" as TodayTaskCommand LOGIC_COLOR
participant "CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : parse("today_task")
activate LogicManager

LogicManager -> SocheduleParser : parseCommand("today_task")
activate SocheduleParser

create TodayTaskCommand
SocheduleParser -> TodayTaskCommand
activate TodayTaskCommand

TodayTaskCommand --> SocheduleParser : s
deactivate TodayTaskCommand

LogicManager <-- SocheduleParser : s
deactivate SocheduleParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SocheduleParser -[hidden]->[

LogicManager -> TodayTaskCommand : execute()
activate TodayTaskCommand

TodayTaskCommand -> Model : updateFilteredTaskList(Predicate<Task> predicate)
activate Model
TodayTaskCommand <-- Model
deactivate Model

create CommandResult
TodayTaskCommand -> CommandResult
activate CommandResult
TodayTaskCommand <-- CommandResult
deactivate CommandResult

LogicManager <-- TodayTaskCommand
deactivate TodayTaskCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
TodayTaskCommand -[hidden]->[
destroy TodayTaskCommand

[<-- LogicManager : CommandResult
@enduml
