@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Interface DictionaryContentConfig <<Interface>>
Interface DictionaryListPanelConfig <<Interface>>
Interface NoteContentConfig <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class ContactListPanel
Class ContactCard
Class DictionaryListPanel
Class DictionaryListContentCard
Class DictionaryListDefinitionCard
Class DictionaryContentPanel
Class NoteListPanel
Class NoteCard
Class NoteContentPanel
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui


ResultDisplay -[hidden]up- HelpWindow
CommandBox -[hidden]up- ResultDisplay
StatusBarFooter -[hidden]up- CommandBox
MainWindow -[hidden]down- Model

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow -left-> HelpWindow
MainWindow *-down-> ResultDisplay
MainWindow *-down-> CommandBox
MainWindow *-down-> ContactListPanel
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> DictionaryListPanel
MainWindow *-down-> NoteListPanel
MainWindow *-right-> NoteContentPanel
MainWindow *-down-> DictionaryContentPanel

NoteListPanel -down-> NoteCard
ContactListPanel -down-> ContactCard
DictionaryListPanel -down-> DictionaryListContentCard
DictionaryListPanel -down-> DictionaryListDefinitionCard


ContactListPanel --[hidden]left- StatusBarFooter
NoteListPanel -[hidden]left- ContactListPanel
DictionaryListPanel -[hidden]left- NoteListPanel

DictionaryContentPanel -[hidden]up- NoteContentPanel

ContactCard .down...> Model
DictionaryListContentCard .down...> Model
DictionaryListDefinitionCard .down...> Model
NoteCard .down...> Model
Model .up...> DictionaryContentConfig
Model .up...> NoteContentConfig

MainWindow -up-> Logic
UiManager -up-> Logic

NoteContentPanel ..|> NoteContentConfig
DictionaryContentPanel ..|> DictionaryContentConfig
DictionaryListPanel .up.|> DictionaryListPanelConfig
DictionaryContentPanel --> DictionaryListPanelConfig


Interface DictionaryContentConfig <<Interface>>

MainWindow --|> UiPart
HelpWindow --|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
ContactListPanel --|> UiPart
StatusBarFooter --|> UiPart
NoteListPanel --|> UiPart
DictionaryListPanel --|> UiPart

NoteCard ---|> UiPart
ContactCard ---|> UiPart
DictionaryListContentCard ---|> UiPart
DictionaryListDefinitionCard ---|> UiPart

DictionaryContentPanel -|> UiPart
NoteContentPanel --|> UiPart



@enduml
