@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonDetails
Class StatusBarFooter
Class CommandBox
Class ImportantDatesWindow
Class ScheduleWindow

Class XYZListPanel

Class XYZCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}


package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> XYZListPanel
MainWindow *-down-> PersonDetails
MainWindow *-down-> StatusBarFooter
MainWindow --> ImportantDatesWindow
MainWindow --> ScheduleWindow
ImportantDatesWindow *-down-> XYZListPanel
PersonDetails *-down-> XYZListPanel
ScheduleWindow *-down-> XYZListPanel

XYZListPanel -down-> XYZCard

MainWindow -down-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonDetails --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart
ImportantDatesWindow -down-|> UiPart
ScheduleWindow -down-|> UiPart
XYZListPanel--|> UiPart
XYZCard --|> UiPart


XYZCard ..> Model
PersonDetails ..> Model
UiManager -right-> Logic
MainWindow -right-> Logic
ImportantDatesWindow -right-> Logic
ScheduleWindow -up-> Logic

ScheduleWindow -[hidden]left- ImportantDatesWindow
ImportantDatesWindow -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
note right of XYZListPanel: XYZListPanel = PersonListPanel, \nDateListPanel, etc
note right of XYZCard: XYZCard = PersonCard, \nDateCard, etc


MainWindow -[hidden]-|> UiPart
@enduml
