@startuml
start
:User executes uncompleted command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (Delivery task that are not marked done present in delivery list) then ([delivery task that are marked done exists])
    :Returns delivery list with all delivery tasks that are not marked done;
else ([else])
    : Return Empty Delivery list;
endif
stop
@enduml
