@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModuleBookParser" as ModuleBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedModuleBook" as VersionedModuleBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ModuleBookParser : parseCommand(undo)
activate ModuleBookParser

create UndoCommand
ModuleBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> ModuleBookParser
deactivate UndoCommand

ModuleBookParser --> LogicManager : u
deactivate ModuleBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoModuleBook()
activate Model

Model -> VersionedModuleBook : undo()
activate VersionedModuleBook

VersionedModuleBook -> VersionedModuleBook :resetData(ReadOnlyModuleBook)
VersionedModuleBook --> Model :
deactivate VersionedModuleBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
