@startuml
start
:User executes command;

if () then ([command format is valid])
    if () then ([task with given index exists])
    :Fetch target task from task list;
        if () then ([target task is completed])
            :Mark target task as uncompleted;
            :Update UI;
        else([else])
        endif
    else ([else])
    endif
else ([else])
endif
stop
@enduml
