@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "undo"

package States <<rectangle>> {
    class State1 as "__tt0:TaskTracker__"
    class State2 as "__tt1:TaskTracker__"
    class State3 as "__tt2:TaskTracker__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State2
@end
