@startuml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "add n/David"

package States <<rectangle>>  {

    object "__pair2:AddressBookCommandPair__" as State3
    State3 : currentCommand = "add n/David"

    object "__ab2:AddressBook__" as ab2

    object "__pair1:AddressBookCommandPair__" as State2
    State2 : currentCommand = "delete 5"

    object "__ab1:AddressBook__" as ab1

    object "__pair0:AddressBookCommandPair__" as State1
    State1 : currentCommand = ""

    object "__ab0:AddressBook__" as ab0
}

State3 -- ab2
State2 -- ab1
State1 -- ab0

@end
