@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DeliverListParser" as DeliveryListParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedDeliveryList" as VersionedDeliveryList MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> DeliveryListParser : parseCommand(undo)
activate DeliveryListParser

create UndoCommand
DeliveryListParser -> UndoCommand
activate UndoCommand

UndoCommand --> DeliveryListParser
deactivate UndoCommand

DeliveryListParser --> LogicManager : u
deactivate DeliveryListParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoAddressBook()
activate Model

Model -> VersionedDeliveryList : undo()
activate VersionedDeliveryList

VersionedDeliveryList -> VersionedDeliveryList :resetData(ReadOnlyAddressBook)
VersionedDeliveryList --> Model :
deactivate VersionedDeliveryList

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
