@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskTrackerParser" as TaskTrackerParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTaskTracker" as VersionedTaskTracker MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> TaskTrackerParser : parseCommand("undo")
activate TaskTrackerParser

create UndoCommand
TaskTrackerParser -> UndoCommand
activate UndoCommand

UndoCommand --> TaskTrackerParser
deactivate UndoCommand

TaskTrackerParser --> LogicManager : u
deactivate TaskTrackerParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoTaskTracker()
activate Model

Model -> VersionedTaskTracker : undo()
activate VersionedTaskTracker

VersionedTaskTracker --> Model : PreviousTaskTracker
deactivate VersionedTaskTracker

Model --> UndoCommand : PreviousTaskTracker
deactivate Model

UndoCommand --> Model : setTaskTracker(PreviousTaskTracker)
activate Model
Model --> UndoCommand
deactivate Model

create CommandResult
UndoCommand -> CommandResult
activate CommandResult

CommandResult --> UndoCommand
deactivate CommandResult

UndoCommand --> LogicManager : result
destroy UndoCommand
UndoCommand -[hidden]-> LogicManager : result

[<--LogicManager
deactivate LogicManager
@enduml
