@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":DeleteCommand" as DeleteCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":Planner" as Planner MODEL_COLOR
participant ":UniqueTagList" as UniqueTagList MODEL_COLOR
end box

[-> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> ModelManager : deleteTag(tag)
activate ModelManager

ModelManager -> Planner : removeTag(tag)
activate Planner

Planner -> UniqueTagList : removeTag(tag)
activate UniqueTagList

UniqueTagList --> Planner
deactivate UniqueTagList

Planner --> ModelManager
deactivate Planner

ModelManager --> DeleteCommand
deactivate ModelManager

[<-- DeleteCommand
deactivate DeleteCommand
@enduml
