@startuml
start
:User attempts to pool a passenger with the pool command;
if () then ([Passenger is already in a pool])
    :User filters the pool list to pools with
    the Passengers name using findPool
    command;
    :Filtered pool list is updated and displayed;
    if () then([Passenger is in the wrong pool])
        :User uses unpool command to remove that pool;
        :pool that contains the passenger is removed;
        :User creates a new pool with the passenger;
    else ([Passenger is in the right pool])
    endif
else ([Passenger does not exist in a pool])
    :New Pool is created;
endif
stop
':User uses unpool [INDEX] command;
':[INDEX] of pool on currently displayed pool list is removed;
'stop
@enduml
