@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":ProjectsFolder" as projectsfolder PROJECTSFOLDER_COLOR
Participant ":UniqueProjectList" as uniqueprojectlist UNIQUEPROJECTLIST_COLOR

user -[USER_COLOR]> ui : "updateP 1 n/Group Project"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("updateP 1 n/Group Project")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : setProject(targetIndex, editedProject)
activate model MODEL_COLOR

model -[MODEL_COLOR]> projectsfolder : setProject(targetIndex, editedProject)
activate projectsfolder PROJECTSFOLDER_COLOR

projectsfolder -[UNIQUEPROJECTLIST_COLOR]> uniqueprojectlist : setProject(targetIndex, editedProject)
activate uniqueprojectlist UNIQUEPROJECTLIST_COLOR

uniqueprojectlist -[UNIQUEPROJECTLIST_COLOR]-> projectsfolder
deactivate uniqueprojectlist


projectsfolder -[PROJECTSFOLDER_COLOR]-> model
deactivate projectsfolder

model -[MODEL_COLOR]-> logic
deactivate model

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
