@startuml
'https://plantuml.com/class-diagram

class User {
  lastUpdated : LocalDate
}

class Age {
  age : int
}

class Bmi {
  weight : double
  height : double
  bmi : double
}

class Gender {
 gender : String
}

class IdealWeight {
 idealWeight : double
}

User --> Age
User --> Bmi
User --> Gender
User --> IdealWeight

@enduml
