@startuml

start
:User executes view command;

if () then ([dog])
:Show dog, owner and programs enrolled;
elseif () then ([owner])
: Show owner and his dogs;
else ([program])
:Shows the program and all enrolled dogs;
endif
:Return View Command;

stop

@enduml
