@startuml
start
:User executes View
        command;

if () then ([valid command])
    :System filters garments
    to view as an outfit;
    :Update garment list;
    :Display garment list;

else ([else])
    :Output invalid command
             format error;
endif

stop
@enduml
