@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":ViewDayCommandParser" as ViewDayCommandParser LOGIC_COLOR
participant ":TaskOnDatePredicate" as TaskOnDatePredicate LOGIC_COLOR
participant ":ViewDayCommand" as ViewDayCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> ViewDayCommandParser : parse(date string)
activate ViewDayCommandParser

create TaskOnDatePredicate
ViewDayCommandParser -> TaskOnDatePredicate : new TaskOnDatePredicate(date)
activate TaskOnDatePredicate

TaskOnDatePredicate --> ViewDayCommandParser : predicate
deactivate TaskOnDatePredicate

create ViewDayCommand
ViewDayCommandParser -> ViewDayCommand : new ViewDayCommand(predicate, local date)
activate ViewDayCommand

ViewDayCommand --> ViewDayCommandParser : command
deactivate ViewDayCommand

[<--ViewDayCommandParser : command
deactivate ViewDayCommandParser

[->ViewDayCommand : execute(model)
activate ViewDayCommand

ViewDayCommand -> Model : updateFilteredTaskList(predicate)
activate Model

Model -> ViewDayCommand
deactivate Model

ViewDayCommand -> Model : setCalendarDate(local date)
activate Model

Model -> ViewDayCommand
deactivate Model

create CommandResult
ViewDayCommand -> CommandResult
activate CommandResult

CommandResult --> ViewDayCommand : commandResult
deactivate CommandResult

[<--ViewDayCommand : commandResult
deactivate ViewDayCommand
@enduml
