@startuml
!include ../style.puml

skinParam DefaultFontSize 18
skinParam ParticipantFontSize 20

box Logic LOGIC_COLOR_T1
Participant ":ViewHistoryCommand" as cmd LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
Participant "model:Model" as model MODEL_COLOR
Participant "hist:ReadOnlyCommandHistory" as cmdHist MODEL_COLOR
end box

-> cmd : execute(model)
activate cmd

cmd -> model : getCommandHistory()
activate model

model --> cmd : hist
deactivate model

loop until each entry to be listed has been read
    cmd -> cmdHist : get(i)
    activate cmdHist
    cmd <-- cmdHist : ith entry
    deactivate cmdHist
end

<-- cmd : cmdHistoryMsg
deactivate cmd
'Hidden arrow to position the destroy marker below the end of the activation bar.
<-[hidden]- cmd
destroy cmd

@enduml
