@startuml
!include ../style.puml

skinParam DefaultFontSize 18
skinParam ParticipantFontSize 20

Participant ":ViewHistoryCommand" as cmd LOGIC_COLOR
Participant "model:Model" as model MODEL_COLOR
Participant "hist:ReadOnlyCommandHistory" as cmdHist MODEL_COLOR

-[LOGIC_COLOR]> cmd : execute(model)
activate cmd LOGIC_COLOR

cmd -[LOGIC_COLOR]> model : getCommandHistory()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> cmd : hist
deactivate model MODEL_COLOR

loop until each entry to be listed has been read
    cmd -[LOGIC_COLOR]> cmdHist : get(i)
    activate cmdHist MODEL_COLOR
    cmd <[MODEL_COLOR]-- cmdHist : ith entry
    deactivate cmdHist
end

<-[LOGIC_COLOR]- cmd : cmdHistoryMsg
deactivate cmd
'Hidden arrow to position the destroy marker below the end of the activation bar.
<-[hidden]- cmd
destroy cmd

@enduml
