@startuml
!include ../style.puml

skinParam DefaultFontSize 18
skinParam ParticipantFontSize 20

box Logic LOGIC_COLOR_T1
Participant ":LogicManager" as logic LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
Participant ":Model" as model MODEL_COLOR
Participant ":CommandHistory" as cmdHist MODEL_COLOR
end box

-> logic : execute("help")
activate logic

logic -> logic : parse and execute "help"
activate logic

logic --> logic
deactivate logic

opt command parsed and executed successfully
    logic -> model : appendCommandHistoryEntry("help")
    'note right: A command is only recorded\n in history if it parses and\n executes successfully
    activate model

    model -> cmdHist : appendEntry("help")
    activate cmdHist

    model <-- cmdHist
    deactivate cmdHist

    model --> logic
    deactivate model
end

<-- logic
deactivate logic

@enduml
