@startuml
!include ../style.puml

skinParam DefaultFontSize 18
skinParam ParticipantFontSize 20

Actor User as user USER_COLOR

box UI UI_COLOR_T1
Participant ":CommandBox" as ui UI_COLOR
end box

box Logic LOGIC_COLOR_T1
Participant ":CommandHistorySelector" as selector LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
Participant ":ReadOnlyCommandHistory" as cmdHist MODEL_COLOR
end box

user -> ui : press UP arrow
activate ui

ui -> selector : selectPreviousUntilFirst()
activate selector

selector -> selector : update state
activate selector

selector --> selector : newSelectedIndex
deactivate selector

selector -> cmdHist : get(newSelectedIndex)
activate cmdHist

cmdHist --> selector : cmdEntry
deactivate cmdHist

selector --> ui : cmdEntry
deactivate selector

ui --> user : display\n cmdEntry
deactivate ui

@enduml
