@startuml
!include ../style.puml
start
:User enters command;
:Parse command text;
if () then ([else])
:Show parsing error
message to user;
stop
else ([parsing successful])
:Execute command;
if () then ([else])
:Show execution error
message to user;
stop
else ([execution successful])
:Append command text
to command history;
:Serialize
command history;
:Save command
history to file;
:Show command
success
message to user;
stop
endif
endif
@enduml
