@startuml
!include ../style.puml
title Adding a Schedule

start
:User executes AddScheduleCommand;

if () then ([all required prefixes present])
      :Parses the prefixes;

      if () then ([all prefixes formatted correctly])
      :Check if schedule already existed;

          if () then ([schedule do not exist])
          :Check if time_From is before time_To;

              if () then ([time_From is before time_To])
              :Check if time_From and
              time_To are in the future;

                  if () then ([time_From and time_To
        are in the future])
                  :Check if time_From is before 6:00 AM;

                      if () then ([time_From is after or equal to 6:00 AM])
                      :Check if time_To is after 11:00 PM;

                          if () then ([time_To is before or equal to 11:00 PM])
                          :Check if the duration is at least 1 hour
                          and not exceeding 8 hours;

                              if () then ([time_To is before or equal to 11:00 PM])
                              :Check if time_From and time_To
                              are in 30 or 60 minutes blocks;

                                  if () then ([time_From and time_To are in 30 or 60 minutes blocks])
                                  :Check if the time_From
                                  and time_To clash with any
                                  existing appointments or events;

                                      if () then ([time_From and time_To does not clash])
                                      :Add schedule to Schedule Tracker;
                                      :Show success message;

                                      else ([else])

                                      :Shows a time slot
                                      clash error message;

                                      endif

                                  else ([else])

                                  :Shows an invalid time
                                  minutes error message;

                                  endif

                              else ([else])

                              :Shows an invalid
                              duration error message;

                              endif

                          else ([else])

                          :Shows an invalid time_To
                          error message;

                          endif

                      else ([else])

                      :Shows an invalid time_From
                      error message;

                      endif

                  else ([else])

                  :Shows an invalid datetime
                  error message;

                  endif

              else ([else])

              :Shows an invalid time
              range error message;

              endif

          else ([else])

          :Shows a duplicate schedule
          error message;

      endif

      else ([else])

      :Shows an error message on
      invalid prefix format;

      endif

else ([else])

    :Shows an invalid command error
    and command format message;
endif

stop

@enduml
