@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "{abstract}\nEvent" as Event

Schedule -up-|> Event
Event *-right-> TimeFrom
Event *-left-> TimeTo

ScheduleTracker *-right-> "1" ScheduleList
ScheduleList o-right-> Schedule

Schedule *--> Title
Schedule *--> Description

@enduml
