@startuml
!include ../style.puml
title Adding a Schedule

start
:User executes AddScheduleCommand;

if () then ([all required prefixes present])
      :Parses the prefixes;

      if () then ([all prefixes formatted correctly])
      :Check if schedule already existed;

          if () then ([schedule do not exist])
          :Check if time_from and time_to are valid;

              if () then ([time_from and time_to is valid])
              :Add schedule to Schedule Tracker;
              :Show success message;

              else ([else])

              :Shows a invalid time slot
              error message;

              endif

          else ([else])

          :Shows a duplicate schedule
          error message;

      endif

      else ([else])

      :Shows an error message on
      invalid prefix format;

      endif

else ([else])

    :Shows an invalid command error
    and command format message;
endif

stop

@enduml
