@startuml
'https://plantuml.com/sequence-diagram

autonumber
-> MainWindow ++ : executeCommand("view 1")
MainWindow -> LogicManager ++: execute("view 1")
LogicManager -> AddressBookParser ++: parseCommand("view 1")
AddressBookParser -> ViewPatientCommandParser**
AddressBookParser <-- ViewPatientCommandParser--
AddressBookParser -> ViewPatientCommand**
AddressBookParser <-- ViewPatientCommand



@enduml
