@startuml
!include Style.puml
hide footbox
title Delete Session Sequence Diagram
skinparam sequenceMessageAlign center

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager
participant ":AddressBookParser" as AddressBookParser
participant ":DeleteSessionCommandParser" as DeleteSessionCommandParser
participant ":DeleteSessionCommand" as DeleteSessionCommand
participant ":CommandResult" as CommandResult
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model
participant ":AddressBook" as AddressBook
end box

-> LogicManager : execute("delete_session c/1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete_session c/1")
activate AddressBookParser

create DeleteSessionCommandParser
AddressBookParser -> DeleteSessionCommandParser
activate DeleteSessionCommandParser

DeleteSessionCommandParser --> AddressBookParser
deactivate DeleteSessionCommandParser

AddressBookParser -> DeleteSessionCommandParser : parse("c/1")
activate DeleteSessionCommandParser

create DeleteSessionCommand
DeleteSessionCommandParser -> DeleteSessionCommand

activate DeleteSessionCommand
DeleteSessionCommandParser <-- DeleteSessionCommand :
deactivate DeleteSessionCommand

DeleteSessionCommandParser --> AddressBookParser :
deactivate DeleteSessionCommandParser

AddressBookParser --> LogicManager :
deactivate AddressBookParser

LogicManager -> DeleteSessionCommand : execute
activate DeleteSessionCommand

DeleteSessionCommand -> Model : deleteSession(sessionToDelete)
activate Model
Model -> AddressBook : removeSession(sessionToDelete)
activate AddressBook
AddressBook --> Model
deactivate AddressBook
Model --> DeleteSessionCommand
deactivate Model

create CommandResult
DeleteSessionCommand -> CommandResult
activate CommandResult
CommandResult --> DeleteSessionCommand
deactivate CommandResult

DeleteSessionCommand --> LogicManager : commandResult
deactivate DeleteSessionCommand
<-- LogicManager
deactivate LogicManager

@enduml
