@startuml
!include Style.puml
hide footbox
title Edit Session Sequence Diagram
skinparam sequenceMessageAlign center

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager
participant ":AddressBookParser" as AddressBookParser
participant ":EditSessionCommandParser" as EditSessionCommandParser
participant ":EditSessionCommand" as EditSessionCommand
participant ":EditSessionDescriptor" as EditSessionDescriptor
participant ":CommandResult" as CommandResult
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model
end box

-> LogicManager : execute("edit_session c/2 d/Monday ts/12:00 to 13:00")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit_session c/2 d/Monday ts/12:00 to 13:00")
activate AddressBookParser

create EditSessionCommandParser
AddressBookParser -> EditSessionCommandParser
activate EditSessionCommandParser

EditSessionCommandParser --> AddressBookParser
deactivate EditSessionCommandParser

AddressBookParser -> EditSessionCommandParser : parse("c/2 d/Monday ts/12:00 to 13:00")
activate EditSessionCommandParser

create EditSessionDescriptor
EditSessionCommandParser -> EditSessionDescriptor
activate EditSessionDescriptor
EditSessionDescriptor --> EditSessionCommandParser : editSessionDescriptor
deactivate EditSessionDescriptor

create EditSessionCommand
EditSessionCommandParser -> EditSessionCommand : EditSessionCommand(c/2 , editSessionDescriptor)

activate EditSessionCommand
EditSessionCommandParser <-- EditSessionCommand :
deactivate EditSessionCommand

EditSessionCommandParser --> AddressBookParser :
deactivate EditSessionCommandParser

AddressBookParser --> LogicManager :
deactivate AddressBookParser

LogicManager -> EditSessionCommand : execute
activate EditSessionCommand

EditSessionCommand -> Model : setSession(sessionToEdit , editedSession)
activate Model
Model --> EditSessionCommand
deactivate Model

create CommandResult
EditSessionCommand -> CommandResult
activate CommandResult
CommandResult --> EditSessionCommand
deactivate CommandResult

EditSessionCommand --> LogicManager : commandResult
deactivate EditSessionCommand
<-- LogicManager
deactivate LogicManager

@enduml
